-- FootballIQ complete database setup v6
-- Safe to run more than once.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text unique,
  rating integer not null default 1000,
  xp integer not null default 0,
  streak integer not null default 0,
  quizzes_completed integer not null default 0,
  correct_answers integer not null default 0,
  total_answers integer not null default 0,
  perfect_quizzes integer not null default 0,
  current_streak integer not null default 0,
  longest_streak integer not null default 0,
  last_activity_date date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles add column if not exists quizzes_completed integer not null default 0;
alter table public.profiles add column if not exists correct_answers integer not null default 0;
alter table public.profiles add column if not exists total_answers integer not null default 0;
alter table public.profiles add column if not exists perfect_quizzes integer not null default 0;
alter table public.profiles add column if not exists current_streak integer not null default 0;
alter table public.profiles add column if not exists longest_streak integer not null default 0;
alter table public.profiles add column if not exists last_activity_date date;
alter table public.profiles add column if not exists updated_at timestamptz not null default now();

create table if not exists public.quiz_results (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  quiz_id text not null,
  score integer not null,
  total integer not null,
  xp_earned integer not null default 0,
  completed_at timestamptz not null default now()
);

create unique index if not exists quiz_results_first_completion
on public.quiz_results(user_id, quiz_id);

create table if not exists public.predictions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  prediction_set text not null,
  fixture_id text not null,
  home_team text not null,
  away_team text not null,
  pick text not null check (pick in ('home','draw','away')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(user_id, prediction_set, fixture_id)
);

alter table public.profiles enable row level security;
alter table public.quiz_results enable row level security;
alter table public.predictions enable row level security;

drop policy if exists "Profiles are readable by everyone" on public.profiles;
create policy "Profiles are readable by everyone" on public.profiles for select using (true);
drop policy if exists "Users can insert their own profile" on public.profiles;
create policy "Users can insert their own profile" on public.profiles for insert with check (auth.uid() = id);
drop policy if exists "Users can update their own profile" on public.profiles;
create policy "Users can update their own profile" on public.profiles for update using (auth.uid() = id) with check (auth.uid() = id);

drop policy if exists "Users can read own quiz results" on public.quiz_results;
create policy "Users can read own quiz results" on public.quiz_results for select using (auth.uid() = user_id);
drop policy if exists "Users can insert own quiz results" on public.quiz_results;
create policy "Users can insert own quiz results" on public.quiz_results for insert with check (auth.uid() = user_id);

drop policy if exists "Users can read own predictions" on public.predictions;
create policy "Users can read own predictions" on public.predictions for select using (auth.uid() = user_id);
drop policy if exists "Users can insert own predictions" on public.predictions;
create policy "Users can insert own predictions" on public.predictions for insert with check (auth.uid() = user_id);
drop policy if exists "Users can update own predictions" on public.predictions;
create policy "Users can update own predictions" on public.predictions for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

create or replace function public.set_updated_at()
returns trigger language plpgsql set search_path = public as $$
begin new.updated_at = now(); return new; end;
$$;

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at before update on public.profiles for each row execute function public.set_updated_at();
drop trigger if exists predictions_set_updated_at on public.predictions;
create trigger predictions_set_updated_at before update on public.predictions for each row execute function public.set_updated_at();

create or replace function public.create_profile_for_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id) values (new.id) on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.create_profile_for_new_user();

create or replace function public.complete_quiz(
  p_quiz_id text,
  p_score integer,
  p_total integer,
  p_xp integer,
  p_activity_date date
)
returns void language plpgsql security definer set search_path = public as $$
declare
  uid uuid := auth.uid();
  previous_date date;
  next_streak integer;
  inserted_count integer;
begin
  if uid is null then raise exception 'Not authenticated'; end if;
  if p_score < 0 or p_total <= 0 or p_score > p_total then raise exception 'Invalid quiz result'; end if;

  insert into public.profiles (id) values (uid) on conflict (id) do nothing;

  insert into public.quiz_results(user_id, quiz_id, score, total, xp_earned)
  values (uid, p_quiz_id, p_score, p_total, p_xp)
  on conflict (user_id, quiz_id) do nothing;

  get diagnostics inserted_count = row_count;
  if inserted_count = 0 then return; end if;

  select last_activity_date, current_streak into previous_date, next_streak from public.profiles where id = uid for update;

  if previous_date = p_activity_date then
    next_streak := greatest(next_streak, 1);
  elsif previous_date = p_activity_date - 1 then
    next_streak := next_streak + 1;
  else
    next_streak := 1;
  end if;

  update public.profiles set
    xp = xp + p_xp,
    rating = greatest(0, rating + ((p_score * 20) - (p_total * 8))),
    quizzes_completed = quizzes_completed + 1,
    correct_answers = correct_answers + p_score,
    total_answers = total_answers + p_total,
    perfect_quizzes = perfect_quizzes + case when p_score = p_total then 1 else 0 end,
    streak = next_streak,
    current_streak = next_streak,
    longest_streak = greatest(longest_streak, next_streak),
    last_activity_date = p_activity_date
  where id = uid;
end;
$$;

grant execute on function public.complete_quiz(text, integer, integer, integer, date) to authenticated;
