-- FootballIQ Player Market Flagship Model Revision V1
-- Apply AFTER SUPABASE_PLAYER_MARKET_MVP.sql
-- Manual apply only. Do not auto-run in production pipelines.

begin;

-- 1) Expand market settings and player lock controls.
alter table if exists public.market_players
  add column if not exists is_trade_locked boolean not null default false,
  add column if not exists trade_lock_reason text,
  add column if not exists trade_lock_started_at timestamptz,
  add column if not exists trade_lock_ends_at timestamptz;

alter table if exists public.market_settings
  add column if not exists max_portfolio_size integer not null default 8,
  add column if not exists sell_spread_bps integer not null default 200,
  add column if not exists season_id text not null default 'S1',
  add column if not exists season_label text not null default 'Season 1',
  add column if not exists season_state text not null default 'open',
  add column if not exists onboarding_enabled boolean not null default true;

alter table if exists public.market_settings
  drop constraint if exists market_settings_max_portfolio_size_check,
  add constraint market_settings_max_portfolio_size_check check (max_portfolio_size between 1 and 30),
  drop constraint if exists market_settings_sell_spread_bps_check,
  add constraint market_settings_sell_spread_bps_check check (sell_spread_bps between 0 and 5000),
  drop constraint if exists market_settings_season_state_check,
  add constraint market_settings_season_state_check check (season_state in ('setup', 'open', 'paused', 'archived'));

update public.market_settings
set max_portfolio_size = 8
where singleton = true
  and coalesce(max_portfolio_size, 0) < 8;

-- 2) Season architecture (manual lifecycle only, no automatic reset).
create table if not exists public.market_seasons (
  season_id text primary key,
  season_label text not null,
  season_state text not null check (season_state in ('setup', 'open', 'paused', 'archived')),
  starts_at timestamptz,
  ends_at timestamptz,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.market_seasons(season_id, season_label, season_state)
values ('S1', 'Season 1', 'open')
on conflict (season_id) do nothing;

create index if not exists market_seasons_state_idx on public.market_seasons(season_state);

drop trigger if exists market_seasons_set_updated_at on public.market_seasons;
create trigger market_seasons_set_updated_at
before update on public.market_seasons
for each row execute function public.market_set_updated_at();

alter table public.market_seasons enable row level security;

drop policy if exists "Public can read market seasons" on public.market_seasons;
create policy "Public can read market seasons"
on public.market_seasons for select
using (true);

-- 3) Rating-event accumulator valuation model.
create table if not exists public.market_rating_events (
  id bigint generated by default as identity primary key,
  external_event_id text not null unique,
  player_id bigint not null references public.market_players(id) on delete cascade,
  match_id text,
  event_timestamp timestamptz not null,
  minutes_played integer not null check (minutes_played between 0 and 130),
  rating_delta numeric(7,3) not null,
  confidence_score numeric(5,3) not null default 1.000 check (confidence_score between 0 and 1),
  source_label text not null,
  source_reference text,
  provenance_status text not null default 'pending_licence_review',
  owner_verified boolean not null default false,
  payload jsonb,
  processed boolean not null default false,
  processed_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.market_player_accumulators (
  player_id bigint primary key references public.market_players(id) on delete cascade,
  hidden_accumulator numeric(12,3) not null default 0,
  last_event_timestamp timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists market_rating_events_player_time_idx
  on public.market_rating_events(player_id, event_timestamp desc);
create index if not exists market_rating_events_processed_idx
  on public.market_rating_events(processed, created_at asc);

drop trigger if exists market_player_accumulators_set_updated_at on public.market_player_accumulators;
create trigger market_player_accumulators_set_updated_at
before update on public.market_player_accumulators
for each row execute function public.market_set_updated_at();

alter table public.market_rating_events enable row level security;
alter table public.market_player_accumulators enable row level security;

-- Public can inspect only verified historical rating events; accumulator remains private.
drop policy if exists "Public can read verified rating events" on public.market_rating_events;
create policy "Public can read verified rating events"
on public.market_rating_events for select
using (owner_verified = true);

-- No select policy on market_player_accumulators: hidden/internal by design.

-- 4) Friends leagues beta.
create table if not exists public.market_friend_leagues (
  id bigint generated by default as identity primary key,
  league_code text not null unique,
  name text not null,
  owner_user_id uuid not null references auth.users(id) on delete cascade,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.market_friend_league_members (
  league_id bigint not null references public.market_friend_leagues(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null default 'member' check (role in ('owner', 'member')),
  joined_at timestamptz not null default now(),
  primary key (league_id, user_id)
);

create index if not exists market_friend_leagues_owner_idx
  on public.market_friend_leagues(owner_user_id, created_at desc);
create index if not exists market_friend_league_members_user_idx
  on public.market_friend_league_members(user_id, joined_at desc);

drop trigger if exists market_friend_leagues_set_updated_at on public.market_friend_leagues;
create trigger market_friend_leagues_set_updated_at
before update on public.market_friend_leagues
for each row execute function public.market_set_updated_at();

alter table public.market_friend_leagues enable row level security;
alter table public.market_friend_league_members enable row level security;

drop policy if exists "League members can read leagues" on public.market_friend_leagues;
create policy "League members can read leagues"
on public.market_friend_leagues for select
using (
  exists (
    select 1
    from public.market_friend_league_members m
    where m.league_id = market_friend_leagues.id
      and m.user_id = auth.uid()
  )
);

drop policy if exists "Users can create leagues" on public.market_friend_leagues;
create policy "Users can create leagues"
on public.market_friend_leagues for insert
with check (auth.uid() = owner_user_id);

drop policy if exists "League owner can update league" on public.market_friend_leagues;
create policy "League owner can update league"
on public.market_friend_leagues for update
using (auth.uid() = owner_user_id)
with check (auth.uid() = owner_user_id);

drop policy if exists "League members can read memberships" on public.market_friend_league_members;
create policy "League members can read memberships"
on public.market_friend_league_members for select
using (
  exists (
    select 1
    from public.market_friend_league_members self
    where self.league_id = market_friend_league_members.league_id
      and self.user_id = auth.uid()
  )
);

drop policy if exists "Users can insert own membership" on public.market_friend_league_members;
create policy "Users can insert own membership"
on public.market_friend_league_members for insert
with check (auth.uid() = user_id);

drop policy if exists "Users can delete own membership" on public.market_friend_league_members;
create policy "Users can delete own membership"
on public.market_friend_league_members for delete
using (auth.uid() = user_id);

create or replace view public.market_friend_league_leaderboard as
select
  l.id as league_id,
  l.name as league_name,
  l.league_code,
  l.owner_user_id,
  m.user_id,
  p.username,
  mp.total_account_value,
  mp.realized_profit_loss,
  mp.portfolio_value,
  row_number() over (partition by l.id order by mp.total_account_value desc, p.username asc) as rank
from public.market_friend_leagues l
join public.market_friend_league_members m on m.league_id = l.id
join public.market_portfolios mp on mp.user_id = m.user_id
left join public.profiles p on p.id = m.user_id
where l.is_active = true;

grant select on public.market_friend_league_leaderboard to authenticated;

-- 5) Utility for 0.1m visible steps.
create or replace function public.market_round_value_step(p_value bigint)
returns bigint
language sql
immutable
as $$
  select (round((p_value::numeric) / 100000) * 100000)::bigint;
$$;

-- 6) Atomic rating-event processor with idempotency + caps.
-- Only service role can execute.
drop function if exists public.market_process_rating_event(text, text, boolean);
create or replace function public.market_process_rating_event(
  p_external_event_id text,
  p_methodology_version text default 'v2.rating-events',
  p_apply boolean default true
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  jwt_role text := coalesce(auth.jwt() ->> 'role', 'anon');
  event_row public.market_rating_events;
  player_row public.market_players;
  accumulator_row public.market_player_accumulators;
  hours_elapsed numeric := 0;
  decay_rate_per_hour numeric := 0.985;
  decayed_accumulator numeric := 0;
  movement_multiplier numeric := 250000;
  per_match_cap bigint := 1200000;
  rolling_week_cap bigint := 2500000;
  minutes_factor numeric := 0;
  raw_movement numeric := 0;
  capped_movement numeric := 0;
  proposed_accumulator numeric := 0;
  available_steps bigint := 0;
  proposed_visible_move bigint := 0;
  applied_visible_move bigint := 0;
  new_value bigint := 0;
  week_anchor_value bigint := 0;
  min_allowed_value bigint := 0;
  max_allowed_value bigint := 0;
begin
  if jwt_role <> 'service_role' then
    raise exception 'Forbidden: service role required';
  end if;

  select * into event_row
  from public.market_rating_events
  where external_event_id = p_external_event_id
  for update;

  if event_row.id is null then
    raise exception 'Rating event not found';
  end if;

  if not event_row.owner_verified then
    raise exception 'Rating event is not owner verified';
  end if;

  if event_row.processed then
    return jsonb_build_object(
      'ok', true,
      'duplicate', true,
      'message', 'Rating event already processed',
      'external_event_id', event_row.external_event_id,
      'player_id', event_row.player_id
    );
  end if;

  select * into player_row
  from public.market_players
  where id = event_row.player_id
  for update;

  if player_row.id is null then
    raise exception 'Player not found for rating event';
  end if;

  insert into public.market_player_accumulators(player_id)
  values (event_row.player_id)
  on conflict (player_id) do nothing;

  select * into accumulator_row
  from public.market_player_accumulators
  where player_id = event_row.player_id
  for update;

  if accumulator_row.last_event_timestamp is not null then
    hours_elapsed := greatest(0, extract(epoch from (event_row.event_timestamp - accumulator_row.last_event_timestamp)) / 3600.0);
  end if;

  decayed_accumulator := accumulator_row.hidden_accumulator * power(decay_rate_per_hour, hours_elapsed);

  minutes_factor := least(1.0, greatest(0.0, (event_row.minutes_played::numeric / 90.0)));
  raw_movement := event_row.rating_delta * movement_multiplier * minutes_factor * event_row.confidence_score;

  if raw_movement > per_match_cap then
    capped_movement := per_match_cap;
  elsif raw_movement < (-1 * per_match_cap) then
    capped_movement := -1 * per_match_cap;
  else
    capped_movement := raw_movement;
  end if;

  proposed_accumulator := decayed_accumulator + capped_movement;

  available_steps := floor(abs(proposed_accumulator) / 100000.0)::bigint;
  if available_steps > 0 then
    proposed_visible_move := available_steps * 100000;
    if proposed_accumulator < 0 then
      proposed_visible_move := proposed_visible_move * -1;
    end if;
  else
    proposed_visible_move := 0;
  end if;

  week_anchor_value := coalesce(
    (
      select h.value
      from public.market_value_history h
      where h.player_id = event_row.player_id
        and h.recorded_at >= (now() - interval '7 days')
      order by h.recorded_at asc
      limit 1
    ),
    player_row.current_value
  );

  min_allowed_value := greatest(0, week_anchor_value - rolling_week_cap);
  max_allowed_value := week_anchor_value + rolling_week_cap;

  new_value := player_row.current_value + proposed_visible_move;
  if new_value < min_allowed_value then
    new_value := min_allowed_value;
  elsif new_value > max_allowed_value then
    new_value := max_allowed_value;
  end if;

  new_value := public.market_round_value_step(new_value);
  applied_visible_move := new_value - player_row.current_value;

  if p_apply and applied_visible_move <> 0 then
    update public.market_players
    set
      previous_value = player_row.current_value,
      current_value = new_value,
      value_updated_at = now()
    where id = player_row.id;

    insert into public.market_value_history(player_id, value, reason_category, methodology_version)
    values (player_row.id, new_value, 'rating_event', p_methodology_version);

    update public.market_settings
    set
      methodology_version = p_methodology_version,
      last_market_update_at = now()
    where singleton = true;
  end if;

  if p_apply then
    update public.market_player_accumulators
    set
      hidden_accumulator = proposed_accumulator - applied_visible_move,
      last_event_timestamp = greatest(coalesce(last_event_timestamp, event_row.event_timestamp), event_row.event_timestamp)
    where player_id = event_row.player_id;

    update public.market_rating_events
    set
      processed = true,
      processed_at = now()
    where id = event_row.id;
  end if;

  return jsonb_build_object(
    'ok', true,
    'duplicate', false,
    'applied', p_apply,
    'external_event_id', event_row.external_event_id,
    'player_slug', player_row.slug,
    'minutes_factor', round(minutes_factor::numeric, 3),
    'raw_movement', round(raw_movement::numeric, 3),
    'capped_movement', round(capped_movement::numeric, 3),
    'applied_visible_move', applied_visible_move,
    'new_value', new_value,
    'accumulator_remainder', round((proposed_accumulator - applied_visible_move)::numeric, 3)
  );
end;
$$;

-- 7) Buy RPC revision: 8-slot capacity + lock checks.
drop function if exists public.market_buy_player(text, text);
create or replace function public.market_buy_player(
  p_player_slug text,
  p_idempotency_key text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  uid uuid := auth.uid();
  market_status text;
  today_utc date := (now() at time zone 'UTC')::date;
  p public.market_portfolios;
  player_row public.market_players;
  holdings_count integer := 0;
  todays_buys integer := 0;
  duplicate_tx public.market_transactions;
  tx public.market_transactions;
  buy_value bigint := 0;
  max_portfolio_size integer := 8;
begin
  if uid is null then
    raise exception 'Not authenticated';
  end if;

  if coalesce(length(trim(p_idempotency_key)), 0) < 8 then
    raise exception 'Invalid idempotency key';
  end if;

  select market_settings.market_status, market_settings.max_portfolio_size
  into market_status, max_portfolio_size
  from public.market_settings
  where singleton = true;

  if market_status is distinct from 'open' then
    raise exception 'Market is currently paused or updating';
  end if;

  select * into duplicate_tx
  from public.market_transactions
  where user_id = uid
    and idempotency_key = p_idempotency_key
  limit 1;

  if duplicate_tx.id is not null then
    perform public.market_ensure_portfolio(uid);
    perform public.market_recalculate_portfolio_totals(uid);
    return jsonb_build_object(
      'ok', true,
      'duplicate', true,
      'message', 'Duplicate request ignored',
      'transaction_id', duplicate_tx.transaction_id
    );
  end if;

  perform public.market_ensure_portfolio(uid);

  select * into p
  from public.market_portfolios
  where user_id = uid
  for update;

  select * into player_row
  from public.market_players
  where slug = p_player_slug
  for update;

  if player_row.id is null then
    raise exception 'Player not found';
  end if;

  if not player_row.active then
    raise exception 'Player is inactive';
  end if;

  if player_row.is_trade_locked and (player_row.trade_lock_ends_at is null or player_row.trade_lock_ends_at > now()) then
    raise exception 'Player trading is temporarily locked: %', coalesce(player_row.trade_lock_reason, 'market review in progress');
  end if;

  buy_value := player_row.current_value;

  select count(*) into holdings_count
  from public.market_holdings
  where user_id = uid;

  if holdings_count >= max_portfolio_size then
    raise exception 'Portfolio is full (maximum % players)', max_portfolio_size;
  end if;

  if exists (
    select 1 from public.market_holdings
    where user_id = uid and player_id = player_row.id
  ) then
    raise exception 'Player already owned';
  end if;

  select count(*) into todays_buys
  from public.market_transactions
  where user_id = uid
    and trade_date_utc = today_utc
    and transaction_type = 'buy';

  if todays_buys >= 3 then
    raise exception 'Daily buy limit reached';
  end if;

  if p.available_balance < buy_value then
    raise exception 'Insufficient balance';
  end if;

  insert into public.market_holdings(
    user_id,
    player_id,
    acquisition_value,
    current_value_snapshot,
    unrealized_profit_loss
  )
  values (uid, player_row.id, buy_value, buy_value, 0);

  insert into public.market_transactions(
    user_id,
    player_id,
    transaction_type,
    execution_value,
    balance_before,
    balance_after,
    idempotency_key
  )
  values (
    uid,
    player_row.id,
    'buy',
    buy_value,
    p.available_balance,
    p.available_balance - buy_value,
    p_idempotency_key
  )
  returning * into tx;

  update public.market_portfolios
  set available_balance = p.available_balance - buy_value
  where user_id = uid;

  perform public.market_recalculate_portfolio_totals(uid);
  perform public.market_capture_snapshot(uid);

  perform public.market_award_xp_event(uid, 'market_first_buy', 25);

  select count(*) into holdings_count
  from public.market_holdings
  where user_id = uid;

  if holdings_count = max_portfolio_size then
    perform public.market_award_xp_event(uid, 'market_first_full_portfolio', 50);
  end if;

  return jsonb_build_object(
    'ok', true,
    'duplicate', false,
    'message', 'Back completed',
    'transaction_id', tx.transaction_id,
    'player_slug', player_row.slug,
    'execution_value', buy_value,
    'max_portfolio_size', max_portfolio_size
  );
exception
  when unique_violation then
    if exists (
      select 1 from public.market_transactions
      where user_id = uid and idempotency_key = p_idempotency_key
    ) then
      return jsonb_build_object('ok', true, 'duplicate', true, 'message', 'Duplicate request ignored');
    end if;
    raise exception 'Back blocked by uniqueness guard';
end;
$$;

-- 8) Sell RPC revision: lock checks + configurable sell spread.
drop function if exists public.market_sell_player(text, text);
create or replace function public.market_sell_player(
  p_player_slug text,
  p_idempotency_key text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  uid uuid := auth.uid();
  market_status text;
  today_utc date := (now() at time zone 'UTC')::date;
  p public.market_portfolios;
  player_row public.market_players;
  holding_row public.market_holdings;
  todays_sales integer := 0;
  duplicate_tx public.market_transactions;
  tx public.market_transactions;
  spread_bps integer := 200;
  gross_value bigint := 0;
  sell_value bigint := 0;
  pnl bigint := 0;
begin
  if uid is null then
    raise exception 'Not authenticated';
  end if;

  if coalesce(length(trim(p_idempotency_key)), 0) < 8 then
    raise exception 'Invalid idempotency key';
  end if;

  select market_settings.market_status, market_settings.sell_spread_bps
  into market_status, spread_bps
  from public.market_settings
  where singleton = true;

  if market_status is distinct from 'open' then
    raise exception 'Market is currently paused or updating';
  end if;

  select * into duplicate_tx
  from public.market_transactions
  where user_id = uid
    and idempotency_key = p_idempotency_key
  limit 1;

  if duplicate_tx.id is not null then
    perform public.market_ensure_portfolio(uid);
    perform public.market_recalculate_portfolio_totals(uid);
    return jsonb_build_object(
      'ok', true,
      'duplicate', true,
      'message', 'Duplicate request ignored',
      'transaction_id', duplicate_tx.transaction_id
    );
  end if;

  perform public.market_ensure_portfolio(uid);

  select * into p
  from public.market_portfolios
  where user_id = uid
  for update;

  select * into player_row
  from public.market_players
  where slug = p_player_slug
  for update;

  if player_row.id is null then
    raise exception 'Player not found';
  end if;

  if not player_row.active then
    raise exception 'Player is inactive';
  end if;

  if player_row.is_trade_locked and (player_row.trade_lock_ends_at is null or player_row.trade_lock_ends_at > now()) then
    raise exception 'Player trading is temporarily locked: %', coalesce(player_row.trade_lock_reason, 'market review in progress');
  end if;

  select * into holding_row
  from public.market_holdings
  where user_id = uid and player_id = player_row.id
  for update;

  if holding_row.id is null then
    raise exception 'Cannot sell: player not owned';
  end if;

  select count(*) into todays_sales
  from public.market_transactions
  where user_id = uid
    and trade_date_utc = today_utc
    and transaction_type = 'sell';

  if todays_sales >= 3 then
    raise exception 'Daily sell limit reached';
  end if;

  gross_value := player_row.current_value;
  sell_value := floor(gross_value::numeric * (1 - (greatest(0, spread_bps)::numeric / 10000)))::bigint;
  sell_value := greatest(0, public.market_round_value_step(sell_value));
  pnl := sell_value - holding_row.acquisition_value;

  delete from public.market_holdings
  where id = holding_row.id;

  insert into public.market_transactions(
    user_id,
    player_id,
    transaction_type,
    execution_value,
    balance_before,
    balance_after,
    idempotency_key
  )
  values (
    uid,
    player_row.id,
    'sell',
    sell_value,
    p.available_balance,
    p.available_balance + sell_value,
    p_idempotency_key
  )
  returning * into tx;

  update public.market_portfolios
  set
    available_balance = p.available_balance + sell_value,
    realized_profit_loss = realized_profit_loss + pnl
  where user_id = uid;

  perform public.market_recalculate_portfolio_totals(uid);
  perform public.market_capture_snapshot(uid);

  if pnl > 0 then
    perform public.market_award_xp_event(uid, 'market_first_profitable_sale', 40);
  end if;

  return jsonb_build_object(
    'ok', true,
    'duplicate', false,
    'message', 'Sale executed',
    'transaction_id', tx.transaction_id,
    'player_slug', player_row.slug,
    'gross_value', gross_value,
    'execution_value', sell_value,
    'sell_spread_bps', spread_bps,
    'profit_loss', pnl
  );
exception
  when unique_violation then
    if exists (
      select 1 from public.market_transactions
      where user_id = uid and idempotency_key = p_idempotency_key
    ) then
      return jsonb_build_object('ok', true, 'duplicate', true, 'message', 'Duplicate request ignored');
    end if;
    raise exception 'Sell blocked by uniqueness guard';
end;
$$;

-- 9) Friends league RPCs.
drop function if exists public.market_create_friend_league(text);
create or replace function public.market_create_friend_league(p_name text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  uid uuid := auth.uid();
  code text;
  new_league public.market_friend_leagues;
  retries integer := 0;
begin
  if uid is null then
    raise exception 'Not authenticated';
  end if;

  if coalesce(length(trim(p_name)), 0) < 3 then
    raise exception 'League name must be at least 3 characters';
  end if;

  loop
    code := upper(substr(md5(random()::text || clock_timestamp()::text), 1, 8));

    begin
      insert into public.market_friend_leagues(league_code, name, owner_user_id)
      values (code, trim(p_name), uid)
      returning * into new_league;
      exit;
    exception
      when unique_violation then
        retries := retries + 1;
        if retries > 8 then
          raise exception 'Could not allocate league code';
        end if;
    end;
  end loop;

  insert into public.market_friend_league_members(league_id, user_id, role)
  values (new_league.id, uid, 'owner')
  on conflict (league_id, user_id) do nothing;

  return jsonb_build_object(
    'ok', true,
    'league_id', new_league.id,
    'league_code', new_league.league_code,
    'name', new_league.name
  );
end;
$$;

drop function if exists public.market_join_friend_league(text);
create or replace function public.market_join_friend_league(p_league_code text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  uid uuid := auth.uid();
  league_row public.market_friend_leagues;
begin
  if uid is null then
    raise exception 'Not authenticated';
  end if;

  select * into league_row
  from public.market_friend_leagues
  where league_code = upper(trim(p_league_code))
    and is_active = true;

  if league_row.id is null then
    raise exception 'League not found';
  end if;

  insert into public.market_friend_league_members(league_id, user_id, role)
  values (league_row.id, uid, 'member')
  on conflict (league_id, user_id) do nothing;

  return jsonb_build_object(
    'ok', true,
    'league_id', league_row.id,
    'league_code', league_row.league_code,
    'name', league_row.name
  );
end;
$$;

drop function if exists public.market_leave_friend_league(bigint);
create or replace function public.market_leave_friend_league(p_league_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  uid uuid := auth.uid();
  league_row public.market_friend_leagues;
begin
  if uid is null then
    raise exception 'Not authenticated';
  end if;

  select * into league_row
  from public.market_friend_leagues
  where id = p_league_id;

  if league_row.id is null then
    raise exception 'League not found';
  end if;

  if league_row.owner_user_id = uid then
    raise exception 'League owner cannot leave. Transfer ownership or deactivate league.';
  end if;

  delete from public.market_friend_league_members
  where league_id = p_league_id
    and user_id = uid;

  return jsonb_build_object('ok', true, 'league_id', p_league_id);
end;
$$;

-- 10) Grants.
grant execute on function public.market_create_friend_league(text) to authenticated;
grant execute on function public.market_join_friend_league(text) to authenticated;
grant execute on function public.market_leave_friend_league(bigint) to authenticated;

grant select on public.market_friend_leagues to authenticated;
grant select on public.market_friend_league_members to authenticated;
grant select on public.market_seasons to anon;
grant select on public.market_seasons to authenticated;
grant select on public.market_rating_events to anon;
grant select on public.market_rating_events to authenticated;

commit;
