-- FootballIQ Market Phase 2: First Playable Loop
-- Apply AFTER SUPABASE_PLAYER_MARKET_FLAGSHIP_PHASE1.sql
-- Manual apply only.

begin;

create table if not exists public.market_matchweek_runs (
  id bigint generated by default as identity primary key,
  initiated_by uuid not null references auth.users(id) on delete cascade,
  week_number integer not null,
  week_label text not null,
  processed_players integer not null,
  biggest_winner_player_id bigint references public.market_players(id) on delete set null,
  biggest_winner_delta bigint not null default 0,
  biggest_loser_player_id bigint references public.market_players(id) on delete set null,
  biggest_loser_delta bigint not null default 0,
  weekly_portfolio_gain bigint not null default 0,
  current_roi_pct numeric(10,3) not null default 0,
  total_profit_since_start bigint not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists market_matchweek_runs_user_created_idx
  on public.market_matchweek_runs(initiated_by, created_at desc);

alter table public.market_matchweek_runs enable row level security;

drop policy if exists "Users can read own matchweek runs" on public.market_matchweek_runs;
create policy "Users can read own matchweek runs"
on public.market_matchweek_runs for select
using (auth.uid() = initiated_by);

-- The run is created by security-definer RPC; no direct insert policy is needed.

drop function if exists public.market_apply_simulated_matchweek(text, jsonb, text);
create or replace function public.market_apply_simulated_matchweek(
  p_week_label text,
  p_player_updates jsonb,
  p_methodology_version text default 'v1.0.0-sim-v1'
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  uid uuid := auth.uid();
  p public.market_portfolios;
  player_row public.market_players;
  update_item jsonb;
  updates_count integer := 0;
  week_number integer := 1;
  portfolio_before bigint := 0;
  portfolio_after bigint := 0;
  weekly_gain bigint := 0;
  roi_pct numeric(10,3) := 0;
  total_profit bigint := 0;
  winner_player_id bigint := null;
  loser_player_id bigint := null;
  winner_delta bigint := -999999999;
  loser_delta bigint := 999999999;
  item_player_id bigint;
  item_new_value bigint;
  item_rating numeric(5,2);
  item_minutes integer;
  item_confidence numeric(5,3);
  old_value bigint;
  delta bigint;
  run_row public.market_matchweek_runs;
begin
  if uid is null then
    raise exception 'Not authenticated';
  end if;

  if jsonb_typeof(p_player_updates) is distinct from 'array' then
    raise exception 'Invalid updates payload';
  end if;

  updates_count := jsonb_array_length(p_player_updates);
  if updates_count = 0 then
    raise exception 'No player updates provided';
  end if;

  perform public.market_ensure_portfolio(uid);
  perform public.market_recalculate_portfolio_totals(uid);

  select * into p
  from public.market_portfolios
  where user_id = uid
  for update;

  if p.user_id is null then
    raise exception 'Portfolio missing';
  end if;

  portfolio_before := coalesce(p.total_account_value, p.starting_balance);

  select coalesce(max(r.week_number), 0) + 1 into week_number
  from public.market_matchweek_runs r
  where r.initiated_by = uid;

  for update_item in
    select value from jsonb_array_elements(p_player_updates)
  loop
    item_player_id := (update_item ->> 'player_id')::bigint;
    item_new_value := (update_item ->> 'new_value')::bigint;
    item_rating := coalesce((update_item ->> 'rating')::numeric, 6.50);
    item_minutes := coalesce((update_item ->> 'minutes_played')::integer, 90);
    item_confidence := coalesce((update_item ->> 'confidence_score')::numeric, 0.900);

    if item_player_id is null or item_new_value is null then
      continue;
    end if;

    if item_new_value < 4000000 then item_new_value := 4000000; end if;
    if item_new_value > 15000000 then item_new_value := 15000000; end if;
    item_new_value := public.market_round_value_step(item_new_value);

    select * into player_row
    from public.market_players
    where id = item_player_id
    for update;

    if player_row.id is null or not player_row.active then
      continue;
    end if;

    old_value := player_row.current_value;
    delta := item_new_value - old_value;

    update public.market_players
    set
      previous_value = current_value,
      current_value = item_new_value,
      value_updated_at = now(),
      updated_at = now()
    where id = player_row.id;

    insert into public.market_value_history(player_id, value, reason_category, methodology_version)
    values (player_row.id, item_new_value, 'matchweek_sim', p_methodology_version);

    insert into public.market_rating_events(
      external_event_id,
      player_id,
      match_id,
      event_timestamp,
      minutes_played,
      rating_delta,
      confidence_score,
      source_label,
      source_reference,
      provenance_status,
      owner_verified,
      payload,
      processed,
      processed_at
    )
    values (
      concat('SIM-', week_number::text, '-', player_row.id::text, '-', extract(epoch from now())::bigint::text),
      player_row.id,
      concat('SIM-MW-', week_number::text),
      now(),
      greatest(0, least(130, item_minutes)),
      (item_rating - 6.75),
      greatest(0, least(1, item_confidence)),
      'owner-simulator',
      p_week_label,
      'owner_seed_demo',
      true,
      jsonb_build_object('rating', item_rating, 'week_label', p_week_label),
      true,
      now()
    );

    if delta > winner_delta then
      winner_delta := delta;
      winner_player_id := player_row.id;
    end if;

    if delta < loser_delta then
      loser_delta := delta;
      loser_player_id := player_row.id;
    end if;
  end loop;

  update public.market_settings
  set
    methodology_version = p_methodology_version,
    last_market_update_at = now()
  where singleton = true;

  perform public.market_recalculate_portfolio_totals(uid);
  perform public.market_capture_snapshot(uid);

  select * into p
  from public.market_portfolios
  where user_id = uid;

  portfolio_after := coalesce(p.total_account_value, portfolio_before);
  weekly_gain := portfolio_after - portfolio_before;
  total_profit := portfolio_after - p.starting_balance;

  if p.starting_balance > 0 then
    roi_pct := round(((portfolio_after - p.starting_balance)::numeric / p.starting_balance::numeric) * 100, 3);
  end if;

  insert into public.market_matchweek_runs(
    initiated_by,
    week_number,
    week_label,
    processed_players,
    biggest_winner_player_id,
    biggest_winner_delta,
    biggest_loser_player_id,
    biggest_loser_delta,
    weekly_portfolio_gain,
    current_roi_pct,
    total_profit_since_start
  )
  values (
    uid,
    week_number,
    coalesce(nullif(trim(p_week_label), ''), concat('Matchweek ', week_number::text)),
    updates_count,
    winner_player_id,
    coalesce(winner_delta, 0),
    loser_player_id,
    coalesce(loser_delta, 0),
    weekly_gain,
    roi_pct,
    total_profit
  )
  returning * into run_row;

  return jsonb_build_object(
    'ok', true,
    'week_number', run_row.week_number,
    'week_label', run_row.week_label,
    'processed_players', run_row.processed_players,
    'biggest_winner', jsonb_build_object(
      'player_id', run_row.biggest_winner_player_id,
      'delta', run_row.biggest_winner_delta,
      'player_name', (select p2.display_name from public.market_players p2 where p2.id = run_row.biggest_winner_player_id)
    ),
    'biggest_loser', jsonb_build_object(
      'player_id', run_row.biggest_loser_player_id,
      'delta', run_row.biggest_loser_delta,
      'player_name', (select p3.display_name from public.market_players p3 where p3.id = run_row.biggest_loser_player_id)
    ),
    'weekly_portfolio_gain', run_row.weekly_portfolio_gain,
    'current_roi_pct', run_row.current_roi_pct,
    'total_profit_since_start', run_row.total_profit_since_start,
    'portfolio_before', portfolio_before,
    'portfolio_after', portfolio_after
  );
end;
$$;

grant execute on function public.market_apply_simulated_matchweek(text, jsonb, text) to authenticated;
grant select on public.market_matchweek_runs to authenticated;

commit;
