import type { Metadata } from 'next'
import { LegalPage } from '@/components/legal-page'

export const metadata: Metadata = { title: 'Player Market Game Rules', description: 'How the Early Shout Player Market works.' }

export default function GameRulesPage() {
  return <LegalPage title="Player Market Game Rules" summary="A plain-language description of the Early Shout Player Market. These rules should be read together with the Terms of Use.">
    <section><h2>1. Free game credits only</h2><p>Each account receives 100m Market Credits for gameplay. Credits have no cash value, cannot be purchased, withdrawn or transferred, and do not represent ownership of a player or any real-world asset.</p></section>
    <section><h2>2. Pick your team and formation</h2><p>Your team needs 11 players. Everyone can choose 4-3-3 (1 goalkeeper, 4 defenders, 3 midfielders and 3 forwards) or 4-4-2 (1 goalkeeper, 4 defenders, 4 midfielders and 2 forwards). The attacking 3-4-3 shape is a permanent Clubhouse reward. You can mix players from any league shown in the Player Market. A formation can only be changed when the players already held fit the new shape.</p></section>
    <section><h2>3. Buy and sell players</h2><p>You can buy up to 11 players in each gameweek if you have enough Market Credits and space in your chosen formation. Sales do not use a signing. The confirm screen shows the exact buy or sale value before you trade. A normal purchase always uses the public market price.</p></section>
    <section id="gameweek-chips"><h2>4. Use one Gameweek Chip</h2><p>You may confirm one chip in each gameweek before the first tracked league match kicks off. Triple Shout gives one held player three times their normal move. Power Pair gives two held players twice their normal move. Position Pulse gives all held defenders, midfielders or forwards 1.5 times their normal move. Full XI Surge gives a complete valid XI 1.2 times their normal move. Lockdown freezes two held players at zero movement. Every boost works up and down, so it can help or hurt. A confirmed chip cannot be changed.</p><p>A chip changes only the value of the exact copies held in your roster when it is confirmed. It does not change the public price paid by other players. Your held adjustment stays through later gameweeks, and a sale pays your held value without changing the public market.</p></section>
    <section><h2>5. How prices change</h2><p>These are Early Shout game prices, not real player values. After a match finishes, we use the player’s rating and minutes to work out a small rise, fall or no change. Limits stop one match from changing a public price too much. A chip is applied afterwards only to eligible copies held by that manager.</p></section>
    <section><h2>6. What happens when data is missing?</h2><p>The price stays the same. We do not guess. Each finished match should change a player’s price only once. If the match data is officially fixed later, we can correct the game price and keep a record of the change.</p></section>
    <section><h2>7. See your results</h2><p>After the price update, the Reveal page shows what happened to your team, each player and any chip adjustment. Leaderboards only compare scores inside this game. Market Credits and player prices are not real money.</p></section>
    <section><h2>8. Pre-launch changes</h2><p>During founder testing, Early Shout may adjust methodology, limits or presentation to improve fairness and reliability. Material rule changes will be documented before broader public play.</p></section>
  </LegalPage>
}
