import type { Metadata } from 'next'
import { LegalPage } from '@/components/legal-page'
import { BRAND } from '@/lib/brand'

export const metadata: Metadata = { title: 'Privacy Notice', description: 'How FootballIQ handles personal data.' }

export default function PrivacyPage() {
  return <LegalPage title="Privacy Notice" summary="This notice explains what information FootballIQ uses, why it is needed, and the choices available to you.">
    <section><h2>1. Controller and contact</h2><p>FootballIQ is the controller for account and gameplay information used by this service. It is operated from Belgium. Privacy questions and rights requests can be sent to <a href={`mailto:${BRAND.supportEmail}`}>{BRAND.supportEmail}</a>.</p></section>
    <section><h2>2. Information we process</h2><ul><li>Account information: email address, user ID, authentication records and username.</li><li>Gameplay information: answers, scores, XP, streaks, predictions, market holdings, transactions, watchlists, gameweek results and league membership.</li><li>Technical information: security, diagnostic and request data produced when the service is used.</li><li>Device storage: essential authentication storage and local or session storage used to save anonymous progress, preferences and import state.</li><li>Usage analytics: limited page and interaction measurements provided through Vercel Analytics when enabled.</li></ul></section>
    <section><h2>3. Purposes and legal bases</h2><ul><li>Provide accounts and gameplay, preserve progress and perform requested transactions: performance of our agreement with you.</li><li>Protect accounts, prevent abuse, diagnose faults and keep an audit trail: our legitimate interests in operating a secure and fair service.</li><li>Comply with valid legal obligations: compliance with law.</li><li>Use non-essential technologies, if introduced: consent where required.</li></ul></section>
    <section><h2>4. Public information</h2><p>Your chosen username and game statistics may appear on public profiles and leaderboards. Your email address is not intended to be public. Do not choose a username containing private information.</p></section>
    <section><h2>5. Service providers and international processing</h2><p>FootballIQ uses Supabase for authentication and database services, Vercel for hosting and analytics, and Sportmonks as a football-data source. These providers process information under their own security and contractual arrangements and may operate infrastructure outside your country. Appropriate safeguards must be used where legally required.</p></section>
    <section><h2>6. Retention</h2><p>Account and gameplay information is generally kept while your account is active and for only as long afterwards as needed for security, dispute resolution, legal duties and backups. Anonymous browser data remains until it expires or you clear it. Retention periods will be reviewed as the beta operating process is finalised.</p></section>
    <section><h2>7. Your rights</h2><p>Depending on applicable law, you may request access, correction, deletion, restriction, portability or object to certain processing. You may withdraw consent where consent is the basis. You may also complain to the Belgian Data Protection Authority or your local supervisory authority. We may need to verify your identity before completing a request.</p></section>
    <section><h2>8. Children</h2><p>FootballIQ does not permit account creation by children under 13. Users below the age required by local law must have valid parental or guardian permission. Contact us if you believe a child’s information has been provided improperly.</p></section>
    <section><h2>9. Security and changes</h2><p>We use access controls, row-level database security and restricted server credentials, but no online service can guarantee absolute security. We will update this notice when processing materially changes and identify the effective date above.</p></section>
  </LegalPage>
}
