import type { Metadata } from 'next'
import { LegalPage } from '@/components/legal-page'
import { BRAND } from '@/lib/brand'

export const metadata: Metadata = { title: 'Privacy Notice', description: 'How Back Your Eye handles personal data.' }

export default function PrivacyPage() {
  const operator = BRAND.legalOperatorName || 'the individual founder of Back Your Eye'
  const address = BRAND.legalOperatorAddress || 'Belgium'
  return <LegalPage title="Privacy Notice" summary="This notice explains what information Back Your Eye uses, why it is needed, and the choices available to you.">
    <section><h2>1. Controller and contact</h2><p>Back Your Eye is operated by {operator}, at {address}. This operator is the controller for account and gameplay information used by the service. Privacy questions and rights requests can be sent to <a href={`mailto:${BRAND.supportEmail}`}>{BRAND.supportEmail}</a>.</p></section>
    <section><h2>2. Information we process</h2><ul><li>Account information: email address, user ID, authentication records and username.</li><li>Gameplay information: answers, scores, XP, streaks, predictions, market holdings, transactions, watchlists, gameweek results and league membership.</li><li>Technical information: security, diagnostic and request data produced when the service is used.</li><li>Device storage: essential authentication storage and local or session storage used to save anonymous progress, preferences and import state.</li><li>Usage analytics: limited page and interaction measurements provided through Vercel Analytics when enabled.</li></ul></section>
    <section><h2>3. Purposes and legal bases</h2><ul><li>Provide accounts and gameplay, preserve progress and perform requested transactions: performance of our agreement with you.</li><li>Protect accounts, prevent abuse, diagnose faults and keep an audit trail: our legitimate interests in operating a secure and fair service.</li><li>Comply with valid legal obligations: compliance with law.</li><li>Use non-essential technologies, if introduced: consent where required.</li></ul></section>
    <section><h2>4. Public information</h2><p>Your chosen username and game statistics may appear on public profiles and leaderboards. Your email address is not intended to be public. Do not choose a username containing private information.</p></section>
    <section><h2>5. Service providers and international processing</h2><p>Back Your Eye uses Supabase for authentication and database services, Vercel for hosting and privacy-focused aggregate web analytics, and Sportmonks as a football-data source. Sportmonks supplies football information rather than Back Your Eye account data. Providers may process service or diagnostic information outside your country. Back Your Eye must maintain appropriate contractual and transfer safeguards where legally required; contact us if you want information about the safeguards relevant to your data.</p></section>
    <section><h2>6. Retention</h2><p>Account and gameplay information is kept while your account is active. After a verified deletion request, live account data will be deleted or anonymised unless a limited record must be retained for security, fraud prevention, dispute resolution or legal compliance. Provider backups and logs may persist for their normal limited backup or security cycles before deletion. Anonymous browser data remains until it expires or you clear it. Beta-participation records may be retained while needed to honour the promised founder benefit or resolve related disputes.</p></section>
    <section><h2>7. Your rights</h2><p>Depending on applicable law, you may request access, correction, deletion, restriction, portability or object to certain processing. You may withdraw consent where consent is the basis. You may also complain to the Belgian Data Protection Authority or your local supervisory authority. We may need to verify your identity before completing a request.</p></section>
    <section><h2>8. Children</h2><p>Back Your Eye does not permit account creation by children under 13 and is not currently marketed to children under 16. Users below the age required by local law must have valid parental or guardian permission. Contact us if you believe a child’s information has been provided improperly.</p></section>
    <section><h2>9. Advertising and sponsorship</h2><p>Direct sponsor messages are contextual and clearly labelled. Aggregate placement views and outbound clicks may be counted. Back Your Eye does not currently use behavioural advertising or provide account and gameplay information to sponsors. If personalised advertising, advertising cookies or a third-party advertising network is introduced later, this notice will be updated and the required consent choices will be shown before those technologies are activated.</p></section>
    <section><h2>10. Security and changes</h2><p>We use access controls, row-level database security and restricted server credentials, but no online service can guarantee absolute security. We will update this notice when processing materially changes and identify the effective date above.</p></section>
  </LegalPage>
}
