'use client'

import Link from 'next/link'
import { SiteHeader } from '@/components/site-header'
import { useAuth } from '@/components/auth-provider'
import { getRankProgress } from '@/lib/progression'

const modes = [
  ['Football Duels', '10 head-to-head quiz packs', '/quizzes/football-duels'],
  ['Higher or Lower', 'Build the longest possible streak', '/quizzes/higher-or-lower'],
  ['Who Am I?', 'Identify players from clues', '/quizzes/who-am-i'],
  ['Career Path', 'Recognise club journeys', '/quizzes/career-path'],
  ['Referee Decisions', 'Apply the Laws of the Game', '/quizzes/referee-decisions'],
  ['Would You Scout Him?', 'Make evidence-based scouting calls', '/quizzes/would-you-scout-him'],
]

export default function HomePage() {
  const { user, profile, loading } = useAuth()
  const rank = getRankProgress(profile?.xp ?? 0)
  return <main className="min-h-screen bg-background"><SiteHeader/><section className="mx-auto max-w-7xl px-4 py-14 sm:px-6">
    {!loading && !user ? <div className="rounded-3xl border border-border bg-card p-8 sm:p-14"><p className="text-sm uppercase tracking-widest text-primary">Test your football brain</p><h1 className="mt-4 max-w-3xl text-5xl font-semibold tracking-tight sm:text-7xl">Build your Football<span className="text-primary">IQ</span></h1><p className="mt-5 max-w-2xl text-lg text-muted-foreground">Six playable game modes, daily challenges, predictions, XP, levels, streaks and a live leaderboard.</p><div className="mt-8 flex gap-3"><Link href="/quizzes" className="rounded-xl bg-primary px-6 py-3 font-medium text-primary-foreground">Start playing</Link><Link href="/signup" className="rounded-xl border border-border px-6 py-3">Create account</Link></div></div> : !loading && user && !profile?.username ? <div className="rounded-3xl border border-border bg-card p-8"><h1 className="text-3xl font-semibold">Finish your FootballIQ profile</h1><p className="mt-3 text-muted-foreground">Choose your public username before you start playing.</p><Link href="/username" className="mt-6 inline-block rounded-xl bg-primary px-6 py-3 font-medium text-primary-foreground">Choose username</Link></div> : <div className="grid gap-5 lg:grid-cols-[1.4fr_.6fr]"><div className="rounded-3xl border border-border bg-card p-8"><p className="text-sm uppercase tracking-widest text-primary">Welcome back</p><h1 className="mt-3 text-4xl font-semibold">Ready, {profile?.username ?? 'player'}?</h1><p className="mt-3 text-muted-foreground">Choose a mode, complete today’s challenge or make your predictions.</p><div className="mt-7 flex flex-wrap gap-3"><Link href="/quizzes/football-duels" className="rounded-xl bg-primary px-6 py-3 font-medium text-primary-foreground">Quick play now</Link><Link href="/quizzes" className="rounded-xl border border-border px-6 py-3">Browse all modes</Link></div></div><div className="rounded-3xl border border-border bg-card p-7"><div className="flex justify-between gap-3"><p className="font-semibold">{rank.current.emoji} {rank.current.title}</p><p className="text-sm text-muted-foreground">{profile?.xp ?? 0} XP</p></div><div className="mt-3 h-3 overflow-hidden rounded-full bg-secondary"><div className="h-full bg-primary" style={{ width: `${rank.percent}%` }}/></div><p className="mt-2 text-xs text-muted-foreground">{rank.next ? `${rank.remaining} XP to ${rank.next.title}` : 'Maximum rank reached'}</p><div className="mt-5 grid grid-cols-2 gap-3 text-sm"><div className="rounded-xl bg-secondary p-3">Rating<br/><strong>{profile?.rating ?? 1000}</strong></div><div className="rounded-xl bg-secondary p-3">Completed<br/><strong>{profile?.quizzes_completed ?? 0}</strong></div><div className="rounded-xl bg-secondary p-3">Streak<br/><strong>{profile?.current_streak ?? 0}</strong></div><div className="rounded-xl bg-secondary p-3">Accuracy<br/><strong>{profile?.total_answers ? Math.round(profile.correct_answers / profile.total_answers * 100) : 0}%</strong></div></div></div></div>}
    <div className="mt-14"><div className="flex items-end justify-between gap-4"><div><h2 className="text-3xl font-semibold">Game modes</h2><p className="mt-2 text-muted-foreground">Everything below is playable in this version.</p></div><Link href="/quizzes" className="text-sm text-primary">View library →</Link></div><div className="mt-7 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{modes.map(([title, desc, href]) => <Link href={href} key={title} className="rounded-3xl border border-border bg-card p-6 transition hover:-translate-y-1 hover:border-primary/60"><h3 className="text-lg font-semibold">{title}</h3><p className="mt-2 text-sm text-muted-foreground">{desc}</p><p className="mt-5 text-xs font-medium uppercase tracking-widest text-primary">Play now</p></Link>)}</div></div>
    <div className="mt-8 grid gap-4 md:grid-cols-2"><Link href="/daily" className="rounded-3xl border border-border bg-card p-7"><p className="text-xs uppercase tracking-widest text-primary">Daily</p><h2 className="mt-2 text-2xl font-semibold">Today’s FootballIQ</h2><p className="mt-2 text-muted-foreground">A fresh five-question challenge tied to your streak.</p></Link><Link href="/predictions" className="rounded-3xl border border-border bg-card p-7"><p className="text-xs uppercase tracking-widest text-primary">Predictions</p><h2 className="mt-2 text-2xl font-semibold">Prediction Challenges</h2><p className="mt-2 text-muted-foreground">Save your picks to your account.</p></Link></div>
  </section></main>
}
