import type { MarketClub, MarketPlayer, MarketSeason } from './types'

const now = new Date().toISOString()

export const DEMO_SEASON: MarketSeason = {
  id: 'demo-2026-27',
  name: 'Demo 2026/27 Season',
  competitionKey: 'demo-premier-league-like',
  seasonKey: 'demo-2026-27',
  startsAt: '2026-08-01T00:00:00.000Z',
  endsAt: '2027-05-31T23:59:59.999Z',
  isActive: true,
  dataUpdatedAt: now,
}

export const DEMO_CLUBS: MarketClub[] = [
  {
    id: 'club-northbridge',
    seasonId: DEMO_SEASON.id,
    providerClubId: 'demo-club-001',
    name: 'Northbridge Athletic',
    shortName: 'Northbridge',
    slug: 'northbridge-athletic',
    primaryColour: '#1b6dff',
    secondaryColour: '#f2f4f8',
    isActive: true,
    dataUpdatedAt: now,
  },
  {
    id: 'club-kingsford',
    seasonId: DEMO_SEASON.id,
    providerClubId: 'demo-club-002',
    name: 'Kingsford United',
    shortName: 'Kingsford',
    slug: 'kingsford-united',
    primaryColour: '#d9343f',
    secondaryColour: '#171717',
    isActive: true,
    dataUpdatedAt: now,
  },
  {
    id: 'club-riverside',
    seasonId: DEMO_SEASON.id,
    providerClubId: 'demo-club-003',
    name: 'Riverside City',
    shortName: 'Riverside',
    slug: 'riverside-city',
    primaryColour: '#2ca35f',
    secondaryColour: '#f6c550',
    isActive: true,
    dataUpdatedAt: now,
  },
]

export const DEMO_PLAYERS: MarketPlayer[] = [
  {
    id: 'player-oren-voss',
    seasonId: DEMO_SEASON.id,
    clubId: 'club-northbridge',
    providerPlayerId: 'demo-player-001',
    fullName: 'Oren Voss',
    displayName: 'O. Voss',
    slug: 'oren-voss',
    positionGroup: 'GK',
    detailedPosition: 'Goalkeeper',
    nationality: 'Demo',
    shirtNumber: 1,
    initialPriceMinor: 94,
    currentPriceMinor: 94,
    performanceBankMilli: 0,
    latestRatingMilli: null,
    isAvailable: true,
    availabilityStatus: 'available',
    dataUpdatedAt: now,
    isDemoSeed: true,
  },
  {
    id: 'player-luca-hale',
    seasonId: DEMO_SEASON.id,
    clubId: 'club-northbridge',
    providerPlayerId: 'demo-player-002',
    fullName: 'Luca Hale',
    displayName: 'L. Hale',
    slug: 'luca-hale',
    positionGroup: 'DEF',
    detailedPosition: 'Centre-back',
    nationality: 'Demo',
    shirtNumber: 4,
    initialPriceMinor: 88,
    currentPriceMinor: 89,
    performanceBankMilli: 100,
    latestRatingMilli: 7100,
    isAvailable: true,
    availabilityStatus: 'available',
    dataUpdatedAt: now,
    isDemoSeed: true,
  },
  {
    id: 'player-milo-trent',
    seasonId: DEMO_SEASON.id,
    clubId: 'club-northbridge',
    providerPlayerId: 'demo-player-003',
    fullName: 'Milo Trent',
    displayName: 'M. Trent',
    slug: 'milo-trent',
    positionGroup: 'MID',
    detailedPosition: 'Holding midfielder',
    nationality: 'Demo',
    shirtNumber: 6,
    initialPriceMinor: 101,
    currentPriceMinor: 100,
    performanceBankMilli: -200,
    latestRatingMilli: 6800,
    isAvailable: true,
    availabilityStatus: 'available',
    dataUpdatedAt: now,
    isDemoSeed: true,
  },
  {
    id: 'player-renzo-valli',
    seasonId: DEMO_SEASON.id,
    clubId: 'club-kingsford',
    providerPlayerId: 'demo-player-004',
    fullName: 'Renzo Valli',
    displayName: 'R. Valli',
    slug: 'renzo-valli',
    positionGroup: 'DEF',
    detailedPosition: 'Right back',
    nationality: 'Demo',
    shirtNumber: 2,
    initialPriceMinor: 86,
    currentPriceMinor: 87,
    performanceBankMilli: 400,
    latestRatingMilli: 7400,
    isAvailable: true,
    availabilityStatus: 'available',
    dataUpdatedAt: now,
    isDemoSeed: true,
  },
  {
    id: 'player-elias-marek',
    seasonId: DEMO_SEASON.id,
    clubId: 'club-kingsford',
    providerPlayerId: 'demo-player-005',
    fullName: 'Elias Marek',
    displayName: 'E. Marek',
    slug: 'elias-marek',
    positionGroup: 'MID',
    detailedPosition: 'Attacking midfielder',
    nationality: 'Demo',
    shirtNumber: 10,
    initialPriceMinor: 109,
    currentPriceMinor: 111,
    performanceBankMilli: 200,
    latestRatingMilli: 7800,
    isAvailable: true,
    availabilityStatus: 'available',
    dataUpdatedAt: now,
    isDemoSeed: true,
  },
  {
    id: 'player-kai-orlov',
    seasonId: DEMO_SEASON.id,
    clubId: 'club-kingsford',
    providerPlayerId: 'demo-player-006',
    fullName: 'Kai Orlov',
    displayName: 'K. Orlov',
    slug: 'kai-orlov',
    positionGroup: 'FWD',
    detailedPosition: 'Centre forward',
    nationality: 'Demo',
    shirtNumber: 9,
    initialPriceMinor: 118,
    currentPriceMinor: 119,
    performanceBankMilli: 300,
    latestRatingMilli: 7300,
    isAvailable: true,
    availabilityStatus: 'available',
    dataUpdatedAt: now,
    isDemoSeed: true,
  },
  {
    id: 'player-tariq-denn',
    seasonId: DEMO_SEASON.id,
    clubId: 'club-riverside',
    providerPlayerId: 'demo-player-007',
    fullName: 'Tariq Denn',
    displayName: 'T. Denn',
    slug: 'tariq-denn',
    positionGroup: 'GK',
    detailedPosition: 'Goalkeeper',
    nationality: 'Demo',
    shirtNumber: 13,
    initialPriceMinor: 90,
    currentPriceMinor: 90,
    performanceBankMilli: 0,
    latestRatingMilli: null,
    isAvailable: true,
    availabilityStatus: 'available',
    dataUpdatedAt: now,
    isDemoSeed: true,
  },
  {
    id: 'player-jasper-kline',
    seasonId: DEMO_SEASON.id,
    clubId: 'club-riverside',
    providerPlayerId: 'demo-player-008',
    fullName: 'Jasper Kline',
    displayName: 'J. Kline',
    slug: 'jasper-kline',
    positionGroup: 'DEF',
    detailedPosition: 'Left back',
    nationality: 'Demo',
    shirtNumber: 3,
    initialPriceMinor: 85,
    currentPriceMinor: 84,
    performanceBankMilli: -500,
    latestRatingMilli: 6500,
    isAvailable: true,
    availabilityStatus: 'available',
    dataUpdatedAt: now,
    isDemoSeed: true,
  },
  {
    id: 'player-ari-navin',
    seasonId: DEMO_SEASON.id,
    clubId: 'club-riverside',
    providerPlayerId: 'demo-player-009',
    fullName: 'Ari Navin',
    displayName: 'A. Navin',
    slug: 'ari-navin',
    positionGroup: 'MID',
    detailedPosition: 'Box-to-box midfielder',
    nationality: 'Demo',
    shirtNumber: 8,
    initialPriceMinor: 95,
    currentPriceMinor: 96,
    performanceBankMilli: 600,
    latestRatingMilli: 7600,
    isAvailable: true,
    availabilityStatus: 'available',
    dataUpdatedAt: now,
    isDemoSeed: true,
  },
  {
    id: 'player-niklas-baird',
    seasonId: DEMO_SEASON.id,
    clubId: 'club-riverside',
    providerPlayerId: 'demo-player-010',
    fullName: 'Niklas Baird',
    displayName: 'N. Baird',
    slug: 'niklas-baird',
    positionGroup: 'FWD',
    detailedPosition: 'Inside forward',
    nationality: 'Demo',
    shirtNumber: 11,
    initialPriceMinor: 112,
    currentPriceMinor: 113,
    performanceBankMilli: 300,
    latestRatingMilli: 7300,
    isAvailable: false,
    availabilityStatus: 'injured',
    dataUpdatedAt: now,
    isDemoSeed: true,
  },
]
