export type DuelOption = { name: string; value: number; detail: string }
export type DuelQuestion = { left: DuelOption; right: DuelOption }
export type DuelPack = { id: string; title: string; description: string; statLabel: string; questions: DuelQuestion[] }

const q = (a: string, av: number, ad: string, b: string, bv: number, bd: string): DuelQuestion => ({ left: { name: a, value: av, detail: ad }, right: { name: b, value: bv, detail: bd } })

export const duelPacks: DuelPack[] = [
  { id: 'pl-goals', title: 'Premier League Goals', description: 'Who scored more Premier League goals?', statLabel: 'PL goals', questions: [
    q('Carlos Tevez',84,'West Ham, Man Utd, Man City','Olivier Giroud',90,'Arsenal, Chelsea'), q('Raheem Sterling',123,'Liverpool, Man City, Chelsea','Sadio Mané',111,'Southampton, Liverpool'), q('Fernando Torres',85,'Liverpool, Chelsea','Dimitar Berbatov',94,'Tottenham, Man Utd, Fulham'), q('Wayne Rooney',208,'Everton, Man Utd','Harry Kane',213,'Tottenham'), q('Cristiano Ronaldo',103,'Manchester United','Olivier Giroud',90,'Arsenal, Chelsea'), q('David Silva',60,'Manchester City','Luis Suárez',69,'Liverpool'), q('Son Heung-min',120,'Tottenham','Raheem Sterling',123,'Liverpool, Man City, Chelsea'), q('Thierry Henry',175,'Arsenal','Frank Lampard',177,'West Ham, Chelsea, Man City'), q('Mohamed Salah',157,'Chelsea, Liverpool','Sergio Agüero',184,'Manchester City'), q('Robin van Persie',144,'Arsenal, Man Utd','Sadio Mané',111,'Southampton, Liverpool') ] },
  { id: 'pl-assists', title: 'Premier League Assists', description: 'Pick the player with more Premier League assists.', statLabel: 'PL assists', questions: [
    q('Cesc Fàbregas',111,'Arsenal, Chelsea','Frank Lampard',102,'West Ham, Chelsea, Man City'), q('Wayne Rooney',103,'Everton, Man Utd','Dennis Bergkamp',94,'Arsenal'), q('David Silva',93,'Manchester City','Steven Gerrard',92,'Liverpool'), q('Kevin De Bruyne',111,'Chelsea, Man City','Cesc Fàbregas',111,'Arsenal, Chelsea'), q('Ryan Giggs',162,'Manchester United','Thierry Henry',74,'Arsenal'), q('James Milner',89,'Multiple clubs','David Beckham',80,'Manchester United'), q('Mohamed Salah',70,'Chelsea, Liverpool','Eden Hazard',54,'Chelsea'), q('Mesut Özil',54,'Arsenal','Juan Mata',52,'Chelsea, Man Utd'), q('Son Heung-min',62,'Tottenham','Sadio Mané',38,'Southampton, Liverpool'), q('Trent Alexander-Arnold',58,'Liverpool','Andrew Robertson',59,'Liverpool') ] },
  { id: 'ucl-goals', title: 'Champions League Goals', description: 'Who has more UEFA Champions League goals?', statLabel: 'UCL goals', questions: [
    q('Karim Benzema',90,'Lyon, Real Madrid','Robert Lewandowski',94,'Dortmund, Bayern, Barcelona'), q('Raúl',71,'Real Madrid, Schalke','Ruud van Nistelrooy',56,'PSV, Man Utd, Real Madrid'), q('Thierry Henry',50,'Monaco, Arsenal, Barcelona','Zlatan Ibrahimović',48,'Multiple clubs'), q('Mohamed Salah',44,'Basel, Roma, Liverpool','Didier Drogba',44,'Marseille, Chelsea, Galatasaray'), q('Sergio Agüero',41,'Atlético, Man City','Edinson Cavani',35,'Napoli, PSG, Man Utd'), q('Neymar',43,'Barcelona, PSG','Kylian Mbappé',48,'Monaco, PSG'), q('Thomas Müller',54,'Bayern Munich','Andriy Shevchenko',48,'Dynamo Kyiv, Milan, Chelsea'), q('Erling Haaland',41,'Salzburg, Dortmund, Man City','Fernando Morientes',33,'Real Madrid, Monaco, Liverpool'), q('Cristiano Ronaldo',140,'Man Utd, Real Madrid, Juventus','Lionel Messi',129,'Barcelona, PSG'), q('Samuel Eto’o',30,'Barcelona, Inter, Chelsea','Wayne Rooney',30,'Manchester United') ] },
  { id: 'world-cup-goals', title: 'World Cup Goals', description: 'Who scored more goals at FIFA World Cups?', statLabel: 'World Cup goals', questions: [
    q('Miroslav Klose',16,'Germany','Ronaldo Nazário',15,'Brazil'), q('Lionel Messi',13,'Argentina','Pelé',12,'Brazil'), q('Kylian Mbappé',12,'France','Thomas Müller',10,'Germany'), q('Gary Lineker',10,'England','Gabriel Batistuta',10,'Argentina'), q('Diego Maradona',8,'Argentina','Cristiano Ronaldo',8,'Portugal'), q('Harry Kane',8,'England','David Villa',9,'Spain'), q('Neymar',8,'Brazil','Luis Suárez',7,'Uruguay'), q('Zinedine Zidane',5,'France','Andrés Iniesta',2,'Spain'), q('Romelu Lukaku',5,'Belgium','Eden Hazard',3,'Belgium'), q('Johan Cruyff',3,'Netherlands','Marco van Basten',0,'Netherlands') ] },
  { id: 'pl-appearances', title: 'Premier League Appearances', description: 'Who played more Premier League matches?', statLabel: 'PL apps', questions: [
    q('Gareth Barry',653,'Aston Villa, Man City, Everton, West Brom','Ryan Giggs',632,'Manchester United'), q('Frank Lampard',609,'West Ham, Chelsea, Man City','David James',572,'Multiple clubs'), q('James Milner',638,'Multiple clubs','Gary Speed',535,'Multiple clubs'), q('Emile Heskey',516,'Multiple clubs','Rio Ferdinand',504,'West Ham, Leeds, Man Utd, QPR'), q('Steven Gerrard',504,'Liverpool','Jamie Carragher',508,'Liverpool'), q('Wayne Rooney',491,'Everton, Man Utd','John Terry',492,'Chelsea'), q('Petr Čech',443,'Chelsea, Arsenal','Peter Schmeichel',310,'Man Utd, Aston Villa, Man City'), q('Ashley Cole',385,'Arsenal, Chelsea','Patrice Evra',278,'Manchester United, West Ham'), q('Sergio Agüero',275,'Manchester City','Didier Drogba',254,'Chelsea'), q('Kevin De Bruyne',260,'Manchester City','David Silva',309,'Manchester City') ] },
  { id: 'international-goals', title: 'International Goals', description: 'Who scored more senior international goals?', statLabel: 'international goals', questions: [
    q('Cristiano Ronaldo',130,'Portugal','Lionel Messi',109,'Argentina'), q('Romelu Lukaku',85,'Belgium','Robert Lewandowski',83,'Poland'), q('Neymar',79,'Brazil','Pelé',77,'Brazil'), q('Harry Kane',66,'England','Wayne Rooney',53,'England'), q('Luis Suárez',69,'Uruguay','Edinson Cavani',58,'Uruguay'), q('Kylian Mbappé',48,'France','Thierry Henry',51,'France'), q('Miroslav Klose',71,'Germany','Gerd Müller',68,'West Germany'), q('Zlatan Ibrahimović',62,'Sweden','Erling Haaland',31,'Norway'), q('Didier Drogba',65,'Ivory Coast','Samuel Eto’o',56,'Cameroon'), q('Sadio Mané',44,'Senegal','Mohamed Salah',57,'Egypt') ] },
  { id: 'pl-clean-sheets', title: 'Premier League Clean Sheets', description: 'Which goalkeeper kept more Premier League clean sheets?', statLabel: 'clean sheets', questions: [
    q('Petr Čech',202,'Chelsea, Arsenal','David James',169,'Multiple clubs'), q('Mark Schwarzer',151,'Multiple clubs','David de Gea',147,'Manchester United'), q('Pepe Reina',136,'Liverpool, Aston Villa','Edwin van der Sar',132,'Fulham, Man Utd'), q('Joe Hart',127,'Man City, West Ham, Burnley, Tottenham','Peter Schmeichel',128,'Man Utd, Aston Villa, Man City'), q('Brad Friedel',132,'Multiple clubs','Shay Given',113,'Multiple clubs'), q('Alisson',86,'Liverpool','Ederson',112,'Manchester City'), q('Thibaut Courtois',48,'Chelsea','Hugo Lloris',128,'Tottenham'), q('Jens Lehmann',54,'Arsenal','Wojciech Szczęsny',72,'Arsenal'), q('Tim Howard',116,'Man Utd, Everton','Jordan Pickford',75,'Everton'), q('David Seaman',141,'Arsenal, Man City','Nigel Martyn',137,'Crystal Palace, Leeds, Everton') ] },
  { id: 'ballon-dor', title: 'Ballon d’Or Wins', description: 'Who won more men’s Ballon d’Or awards?', statLabel: 'Ballon d’Ors', questions: [
    q('Lionel Messi',8,'Argentina','Cristiano Ronaldo',5,'Portugal'), q('Johan Cruyff',3,'Netherlands','Michel Platini',3,'France'), q('Ronaldo Nazário',2,'Brazil','Ronaldinho',1,'Brazil'), q('Zinedine Zidane',1,'France','Kaká',1,'Brazil'), q('Marco van Basten',3,'Netherlands','Ruud Gullit',1,'Netherlands'), q('George Best',1,'Northern Ireland','Bobby Charlton',1,'England'), q('Karim Benzema',1,'France','Luka Modrić',1,'Croatia'), q('Thierry Henry',0,'France','Andriy Shevchenko',1,'Ukraine'), q('Xavi',0,'Spain','Andrés Iniesta',0,'Spain'), q('Neymar',0,'Brazil','Luis Suárez',0,'Uruguay') ] },
  { id: 'premier-league-titles', title: 'Premier League Titles', description: 'Who won more Premier League titles as a player?', statLabel: 'PL titles', questions: [
    q('Ryan Giggs',13,'Manchester United','Paul Scholes',11,'Manchester United'), q('John Terry',5,'Chelsea','Rio Ferdinand',6,'Manchester United'), q('Sergio Agüero',5,'Manchester City','Didier Drogba',4,'Chelsea'), q('Kevin De Bruyne',6,'Manchester City','David Silva',4,'Manchester City'), q('Thierry Henry',2,'Arsenal','Wayne Rooney',5,'Manchester United'), q('Mohamed Salah',1,'Liverpool','Eden Hazard',2,'Chelsea'), q('Petr Čech',4,'Chelsea','Edwin van der Sar',4,'Manchester United'), q('Cristiano Ronaldo',3,'Manchester United','Eric Cantona',4,'Manchester United'), q('Ashley Cole',3,'Arsenal, Chelsea','Patrice Evra',5,'Manchester United'), q('Jamie Vardy',1,'Leicester City','Harry Kane',0,'Tottenham') ] },
  { id: 'euro-goals', title: 'European Championship Goals', description: 'Who scored more goals at the UEFA European Championship finals?', statLabel: 'EURO goals', questions: [
    q('Cristiano Ronaldo',14,'Portugal','Michel Platini',9,'France'), q('Antoine Griezmann',7,'France','Alan Shearer',7,'England'), q('Harry Kane',7,'England','Wayne Rooney',6,'England'), q('Álvaro Morata',7,'Spain','Fernando Torres',5,'Spain'), q('Zlatan Ibrahimović',6,'Sweden','Thierry Henry',6,'France'), q('Romelu Lukaku',6,'Belgium','Ruud van Nistelrooy',6,'Netherlands'), q('Kylian Mbappé',1,'France','Karim Benzema',4,'France'), q('Marco van Basten',5,'Netherlands','Dennis Bergkamp',4,'Netherlands'), q('David Villa',4,'Spain','Andrés Iniesta',0,'Spain'), q('Mario Balotelli',3,'Italy','Andrea Pirlo',2,'Italy') ] },
]
