export type TruthTrapDifficulty = 'Starter' | 'Sharp' | 'Expert'

export type TruthTrapQuestion = {
  id: string
  kind: 'truth-trap'
  difficulty: TruthTrapDifficulty
  prompt: string
  options: string[]
  answer: string
  explanation: string
  takeaway: string
}

type Trap = { label: string; reason: string }
type TruthGroup = {
  difficulty: TruthTrapDifficulty
  prompt: string
  truths: [string, string, string]
  traps: [Trap, Trap, Trap, Trap]
  takeaway: string
}

const g = (difficulty: TruthTrapDifficulty, prompt: string, truths: [string, string, string], traps: [Trap, Trap, Trap, Trap], takeaway: string): TruthGroup => ({ difficulty, prompt, truths, traps, takeaway })
const t = (label: string, reason: string): Trap => ({ label, reason })

const truthGroups: TruthGroup[] = [
  g('Starter','Which statement about a throw-in is false?',['The ball is delivered with both hands','The ball comes from behind and over the head','Both feet must meet the touchline rule at release'],[t('Both feet must be completely inside the field','part of each foot may be on or outside the touchline'),t('The thrower may use one hand','the ball must be delivered with both hands'),t('A legal throw may come from chest height','the release must come from behind and over the head'),t('Opponents may stand against the thrower','opponents must respect the required distance')],'Watch the release, feet and distance—not an invented rule.'),
  g('Starter','Which statement about common restarts is false?',['A throw-in follows the ball crossing a touchline','A corner can follow a defender’s last touch over the goal line','A kick-off starts each half'],[t('A goal kick follows every shot off target','the last touch decides whether it is a goal kick or corner'),t('A corner is taken from the centre circle','it is taken from the relevant corner area'),t('A throw-in can directly score a goal','a goal cannot be scored directly from a throw-in'),t('A kick-off must travel forward','the ball may move in any direction once kicked and clearly moves')],'First identify the boundary and the last touch.'),
  g('Starter','Which statement about player positions is false?',['A centre-back usually protects central depth','A winger often gives width or attacks inside','A holding midfielder can screen the defence'],[t('A goalkeeper normally leads the highest attacking line','the goalkeeper is normally the deepest player'),t('A centre-forward must stay inside the centre circle','forwards move across and beyond the attacking line'),t('A full-back may never enter midfield','some roles deliberately move inside'),t('Every position has one fixed movement','roles adapt to the phase and game plan')],'Use a role’s main job as a starting point, not a cage.'),
  g('Starter','Which statement about passing is false?',['Body shape can open the next pass','Scanning helps a player see pressure','Pass weight affects the receiver’s next action'],[t('The hardest pass is always the best pass','the useful pass depends on distance, pressure and purpose'),t('A player should look only at the ball','information away from the ball guides the decision'),t('Every pass should go forward','circulation can move pressure and create a better route'),t('Accuracy alone proves a pass was useful','risk, purpose and opportunity also matter')],'A good pass helps the next action, not only the completion total.'),
  g('Starter','Which statement about defending is false?',['Goal-side position can protect the route to goal','A delay can buy recovery time','Communication can prevent danger before a tackle'],[t('Every defender should chase the ball','connected cover matters more than a crowd around the ball'),t('Contact automatically makes a challenge a foul','football allows fair physical contact'),t('The deepest line should ignore runners','tracking and passing on runners are core jobs'),t('A clearance is always better than controlled possession','the safest useful action depends on pressure and space')],'Defend the danger together, not the ball alone.'),
  g('Starter','Which statement about shooting is false?',['Shot choice should reflect angle and pressure','A cut-back can create a clearer finish','Composure can matter as much as power'],[t('Every shot should be hit at maximum power','placement and timing can be better'),t('A blocked lane is always the best moment to shoot','a pass or touch may create a clearer lane'),t('Long-range shots are worth more goals','a goal counts the same regardless of distance'),t('A striker should never use the weaker foot','using either foot can turn a chance into a shot')],'Choose the finish the picture gives you.'),
  g('Starter','Which statement about goalkeepers is false?',['Starting position affects sweeping','Communication can prevent shots','Distribution choices affect build-up'],[t('Save totals tell the whole story','shot quality and team context strongly affect save volume'),t('A goalkeeper should remain on the goal line for every attack','starting position changes with the ball and defensive line'),t('Handling is the only goalkeeper skill','claiming, movement, passing and decisions also matter'),t('Every cross must be caught','punching, holding position or claiming can each be correct')],'Judge the full action and the context around it.'),
  g('Starter','Which statement about learning football is false?',['Feedback should explain why','Replaying later can strengthen recall','Clear questions need one best answer'],[t('Confusing wording makes a quiz more expert','difficulty should come from football thinking'),t('A wrong answer teaches nothing','useful feedback can turn it into learning'),t('The score matters more than understanding','knowing why improves future decisions'),t('Guessing quickly is always the best strategy','careful reading is often part of the skill')],'The challenge should be football, not messy wording.'),
  g('Starter','Which statement about team communication is false?',['Useful calls are early and clear','A warning about pressure can help a receiver','Praise can support confidence'],[t('Blaming during live play solves the next action','blame distracts from the immediate problem'),t('Two opposite instructions are better than one','conflicting calls create confusion'),t('Silence is best when a runner is free','early information can prevent danger'),t('Only the captain should communicate','all players share useful information')],'Say what helps the next action.'),
  g('Starter','Which statement about recovery is false?',['Sleep supports adaptation','Hydration matters','Training load should rise sensibly'],[t('Pain should always be ignored','pain can be a warning that needs assessment'),t('Every day must be maximal intensity','recovery and varied load protect quality'),t('Warm-ups waste useful energy','a suitable warm-up prepares body and mind'),t('More work is automatically better work','purpose and recovery affect the value of training')],'Good development includes the work between hard sessions.'),
  g('Starter','Which statement about mini leagues is false?',['Rules should be visible','A join code can connect friends','A clear time window prevents disputes'],[t('The owner may secretly change results','competition needs transparent scoring'),t('Players should discover the rules after playing','rules belong before the contest starts'),t('Only the winner should see the table','shared standings make the competition understandable'),t('A code should be posted publicly by default','private groups should control who can enter')],'Friendly competition still needs trusted rules.'),
  g('Starter','Which statement about fair player comparison is false?',['Role context matters','The opposition level matters','A larger sample is safer than one clip'],[t('One highlight proves the full player','a highlight is a tiny, selected sample'),t('Two different roles can be compared by raw totals alone','opportunity and job shape the numbers'),t('Age and competition can be ignored','development stage and level change the meaning'),t('Popularity is performance evidence','attention does not prove match quality')],'Compare like with like and write down the context.'),
  g('Sharp','Which statement about pressing is false?',['The first presser needs support','The team should protect the middle','Distances between lines matter'],[t('Every player should sprint at the ball independently','uncoordinated pressure opens simple passes'),t('The back line should stay far behind','that stretches the pressing team'),t('Each player should choose a different trigger','shared timing makes the press connected'),t('The far side should stay completely open','narrowing can remove the easy switch')],'One player presses; the team closes the next options.'),
  g('Sharp','Which statement about a high press is false?',['A poor touch can be a trigger','A curved run can block one pass','The defensive line may squeeze behind'],[t('Noise from the crowd is the main tactical trigger','the opponent’s control and options matter'),t('The nearest presser should ignore body shape','the angle can show play toward the trap'),t('Cover players can stop moving','support must adjust as the ball moves'),t('Winning the ball is the only successful outcome','forcing a clearance can also achieve the aim')],'Judge whether the press controls the next pass.'),
  g('Sharp','Which statement about counter-pressing is false?',['Nearby players react first','The centre is often protected quickly','The team may stop an immediate counter'],[t('Everyone should run toward the exact ball spot','crowding one point can expose the next pass'),t('Rest defence is unrelated','players behind the attack make the reaction safer'),t('The reaction can wait until the opponent settles','the first seconds are usually the key window'),t('A broken counter-press should continue forever','the team may need to recover into shape')],'React fast, then know when to recover.'),
  g('Sharp','Which statement about counter-attacks is false?',['The first touch can secure the regain','Runners can use different lanes','The ball carrier should scan'],[t('Every runner should crowd the ball','width and depth force defenders to choose'),t('The first pass must always go forward','sometimes control or a safe release protects the opportunity'),t('Speed removes the need for spacing','fast attacks still need clear lanes'),t('The attack should ignore the goalkeeper’s position','the final action depends on the full picture')],'Fast play still needs information and spacing.'),
  g('Sharp','Which statement about build-up against a press is false?',['Width and depth create choices','The goalkeeper can be an extra passer','Moving the ball can move the press'],[t('All players should stand on one line','different heights create better angles'),t('The spare player should hide behind a marker','they must become visible to the ball'),t('A long pass is always a failure','going over pressure can be the correct route'),t('The team should force the same exit every time','varying routes makes the press harder to set')],'Create the free route, then use it.'),
  g('Sharp','Which statement about playing through midfield is false?',['Scanning before receiving helps','A third-player run can beat pressure','Different heights improve passing angles'],[t('The pivot should receive square to their own goal every time','body shape should fit the pressure and next action'),t('More players in one tiny space always helps','crowding can remove time and lanes'),t('The first forward option must be forced','circulation may open a cleaner route'),t('Support behind the ball is unnecessary','a bounce option can protect possession')],'Give the receiver information, angles and an exit.'),
  g('Sharp','Which statement about attacking a low block is false?',['Width can stretch it','Rotations can move defenders','Cut-backs can attack space behind midfield'],[t('Hopeful crosses are the only answer','switches, combinations and varied box occupation also work'),t('Every attacker should stand on the last line','different heights can connect and disrupt the block'),t('The ball should stay on one side forever','switching can attack the weak side'),t('Rest defence can be ignored','a secure base protects against the counter')],'Change the picture before forcing the final ball.'),
  g('Sharp','Which statement about overloads is false?',['An extra player can create a free option','The ball can attract a defender','A third-player action can release the spare'],[t('An overload guarantees success','timing, spacing and execution still decide the outcome'),t('Every extra player should stand beside the ball','different angles make the advantage usable'),t('The far side never matters','the switch may be the reward for drawing pressure'),t('The defender’s reaction can be ignored','the next action depends on who jumps')],'Create the advantage, then read the defender.'),
  g('Sharp','Which statement about width is false?',['It can stretch a narrow defence','It can open inside lanes','A full-back or winger may provide it'],[t('Maximum width is correct in every phase','the best width changes with location and risk'),t('Both wide players must always hug the touchline','one may move inside while another holds width'),t('Width matters only near the corner flag','it shapes build-up and progression too'),t('A wide player should never combine inside','width can create the angle for an inside action')],'Use width to create space, not as a fixed rule.'),
  g('Sharp','Which statement about depth is false?',['A run behind can stretch the line','A short option can connect play','Different heights create passing choices'],[t('Every player should come toward the ball','the team then loses threat behind'),t('Depth means hitting a long ball every time','movement can create space even without receiving'),t('The deepest runner should always be the striker','wide or midfield players can attack behind'),t('A team can attack with no one beyond the ball','without depth the defence can step up freely')],'Offer options to feet and beyond.'),
  g('Sharp','Which statement about crossing is false?',['Delivery should match the runs','Box occupation affects the chance','Cut-backs and clipped crosses create different pictures'],[t('Every cross should target the same zone','variation should respond to space and movement'),t('The crosser need not scan','the best delivery depends on runners and defenders'),t('More attackers in the box always means a safer attack','rest defence and spacing still matter'),t('A blocked crossing lane should be ignored','a new touch or combination may create a cleaner delivery')],'Deliver to the movement you can see.'),
  g('Sharp','Which statement about set pieces is false?',['Roles should be clear','The delivery needs a cue','Counter-attack cover matters'],[t('Players can invent new jobs after the kick','the routine needs shared timing'),t('Every corner should use the same routine','variation can exploit different opponents'),t('Only the taker needs to know the plan','runs, blocks and protection must connect'),t('The second ball is irrelevant','many set-piece chances continue after first contact')],'Clarity starts the routine; reaction finishes it.'),
  g('Sharp','Which statement about substitutions is false?',['The match problem comes first','The new role should be explained','The effect should be reviewed'],[t('The highest-rated player must always enter','the useful profile depends on the problem'),t('Game state does not affect the choice','score and time shape risk'),t('A change works without team-mate communication','the surrounding roles may need adjustment'),t('A substitution is successful once the player crosses the line','the coach still needs to assess the outcome')],'Choose the profile the match needs.'),
  g('Sharp','Which statement about protecting a lead is false?',['Central routes need protection','An outlet can relieve pressure','Safe possession can reduce opponent attacks'],[t('Every player should remain inside the penalty box','that invites repeated pressure and removes an exit'),t('The team should stop reading new threats','opponents often change shape and risk'),t('Clearances should always be blind','territory and possession are useful when available'),t('Time alone will solve every attack','the team still needs active decisions')],'Control space and keep a way out.'),
  g('Sharp','Which statement about chasing a game is false?',['More useful box occupation can help','Rest defence still matters','The ball may need to move faster'],[t('Every player should become a striker','that removes structure and supply'),t('Risk should increase with no plan','extra risk should target a specific problem'),t('The widest player should always abandon width','width may be needed to move the block'),t('Defenders can ignore counter-attacks','one opponent break can finish the game')],'Increase threat without removing all control.'),
  g('Sharp','Which statement about playing with ten is false?',['Compactness becomes important','Pressing moments must be chosen','The team can protect central spaces first'],[t('The missing player can be ignored','roles and coverage must be redistributed'),t('The team must press every pass','constant pressure can open fatal gaps'),t('Possession is now forbidden','keeping the ball can provide recovery'),t('All attacking threat should disappear','an outlet can still stop endless pressure')],'Remove wasted movement, not every attacking idea.'),
  g('Sharp','Which statement about a winger is false?',['One-versus-one threat can create advantages','Runs behind can stretch the line','Back-post arrivals can produce chances'],[t('Dribbles completed tell the whole role','movement, decisions and team context also matter'),t('A winger should never pass backwards','a bounce pass can protect or reset the attack'),t('Holding width is always passive','it can create space for team-mates inside'),t('Defensive reactions are irrelevant','many game plans require pressing and recovery')],'Judge threat on and away from the ball.'),
  g('Sharp','Which statement about a number six is false?',['The role can screen central passes','The player can connect build-up','Position affects counter protection'],[t('The number six should chase every opponent','leaving the centre can expose the defence'),t('Safe passing means never playing forward','the role can break lines when the picture allows'),t('Only tackles show defensive value','positioning can prevent the pass before it arrives'),t('The player should always stand between centre-backs','the best height depends on pressure and structure')],'Protect the centre and give the team a clean next pass.'),
  g('Sharp','Which statement about centre-backs is false?',['Cover and pressure should connect','Body shape helps track ball and runner','Communication controls the line'],[t('Winning every duel proves perfect defending','avoiding dangerous duels can be even better'),t('Aerial totals need no context','delivery quality and opponent matter'),t('Progressive passing is always reckless','a controlled line-break can help the team'),t('The nearest centre-back must attack every ball','cover, goalkeeper position and runner threat affect the choice')],'Defend the whole picture, not one duel total.'),
  g('Sharp','Which statement about full-backs is false?',['They may overlap or underlap','Back-post awareness matters','Recovery position affects transition defence'],[t('A full-back must play on the touchline at all times','some structures move the role inside'),t('Attacking output erases defensive decisions','both phases matter'),t('Pace alone defines the role','timing, scanning and technique can compensate'),t('Both full-backs should always attack together','the team may stagger them for balance')],'Read the role inside the team’s structure.'),
  g('Sharp','Which statement about strikers is false?',['Movement can create space for others','Pressing angles can guide build-up','Link play can connect attacks'],[t('Goals alone describe every performance','chance quality, movement and team service matter'),t('Dropping short is always helpful','it can crowd midfield or remove depth'),t('The striker must touch the ball to affect defenders','runs can move the line without receiving'),t('Every shot should be taken first time','control may create a better finish')],'Track how the striker creates, connects and finishes.'),
  g('Sharp','Which statement about scouting is false?',['Context can change the evidence weight','Missing evidence should be written down','Role fit can change a recommendation'],[t('One match proves the player’s ceiling','a single match is only a sample'),t('A recommendation should hide uncertainty','decision-makers need to know what remains unknown'),t('Highlights are a complete evidence set','selected clips omit many actions'),t('The scout should begin with the final verdict','observation should come before judgement')],'Evidence first; recommendation last.'),
  g('Sharp','Which statement about youth scouting is false?',['Development can be non-linear','Physical maturity affects comparison','Technical habits can project beyond current output'],[t('The biggest player at 14 is automatically the best prospect','maturity can temporarily distort performance'),t('One age group tells the full story','players face different demands as they progress'),t('Late developers should be removed immediately','growth timelines vary'),t('Current goals guarantee senior success','translation depends on many skills and contexts')],'Project carefully and leave room for change.'),
  g('Sharp','Which statement about data analysis is false?',['A useful number needs context','Opportunity affects raw totals','Trends can be safer than one match'],[t('A high total always means high quality','volume may reflect role or opportunity'),t('The denominator is optional','rates need the relevant opportunity base'),t('Data removes the need for video','numbers and football context answer different parts'),t('One metric should decide recruitment','multi-dimensional decisions need broader evidence')],'Ask what produced the number.'),
  g('Sharp','Which statement about video review is false?',['A clear question focuses the clips','Opposition and game state matter','Contradicting examples should be considered'],[t('Only successful actions belong in the review','mistakes and near-misses reveal patterns'),t('The first clip should decide the conclusion','patterns need a meaningful sample'),t('Every clip has the same context','role and match situation change meaning'),t('A montage proves causation','selected sequences can hide alternative explanations')],'Use clips to test an idea, not decorate a verdict.'),
  g('Sharp','Which statement about confidence is false?',['Confidence can change decisions','Clear roles can reduce hesitation','Support after mistakes can help recovery'],[t('Public blame always improves performance','it can increase fear and distract learning'),t('Confidence means ignoring feedback','secure players can still review honestly'),t('One mistake proves a player lacks mentality','single events do not define a person'),t('The loudest player is always the most confident','communication style and confidence are not identical')],'Build clarity and recovery, not fear.'),
  g('Sharp','Which statement about leadership is false?',['Leaders can organise early','They can model reactions after mistakes','Listening can be part of leadership'],[t('Leadership belongs only to the captain','many players can lead actions and standards'),t('Shouting more makes every message better','timing and clarity matter more than volume'),t('A leader should never admit uncertainty','honest questions can improve decisions'),t('Leadership is unrelated to behaviour','actions often carry more weight than speeches')],'Useful leadership makes the next action clearer.'),
  g('Sharp','Which statement about game state is false?',['Score affects acceptable risk','Time remaining affects urgency','Player numbers change space and workload'],[t('The same plan is best in every game state','priorities should respond to the situation'),t('A one-goal lead removes all attacking need','an outlet and possession can protect the lead'),t('Trailing means structure no longer matters','chaos can help the opponent as much as you'),t('A red card changes only one position','the whole team’s coverage can change')],'Read score, time and numbers before choosing risk.'),
  g('Sharp','Which statement about advantage is false?',['It should offer an immediate benefit','Possession alone may not be enough','Some misconduct can be handled at the next stoppage'],[t('It must be played after every foul','sometimes the free kick is the better benefit'),t('The referee should ignore location','field position affects the value of continuing'),t('A team under pressure always has advantage','control and attacking promise matter'),t('A serious safety incident should never stop play','player safety can require an immediate stoppage')],'Ask what the fouled team gains now.'),
  g('Sharp','Which statement about cautions is false?',['Reckless challenges require a caution','Some tactical fouls can stop promising attacks','Dissent can be misconduct'],[t('Every careless foul requires yellow','careless alone is normally a foul without automatic caution'),t('A yellow card changes the restart','discipline and restart are separate decisions'),t('Only tackles can earn cautions','behaviour and other offences can also be cautioned'),t('A second caution lets the player remain','a second caution leads to sending-off')],'Separate foul severity, misconduct and restart.'),
  g('Sharp','Which statement about handball is false?',['Not every touch is an offence','Arm position can matter','The action and context must be judged'],[t('Any ball-to-hand contact is automatically handball','the Law uses specific offence criteria'),t('Intent is the only possible consideration','unnatural position and other criteria can matter'),t('A team-mate’s accidental touch always cancels a later goal','non-scorer accidental contact is not automatically punished solely because a goal follows'),t('The referee can judge without seeing the arm','the actual position and movement are essential evidence')],'Contact begins the question; it does not finish it.'),
  g('Sharp','Which statement about offside position is false?',['It is judged at a team-mate’s play or touch','Position alone is not an offence','A player can interfere with an opponent'],[t('Any defender touch resets offside','a deflection or deliberate save does not reset it like a deliberate play can'),t('A player in their own half can be offside','a player cannot be in an offside position in their own half'),t('Hands and arms set the offside line','the relevant playable body parts are used'),t('Every player beyond the ball is punished','involvement and position criteria still apply')],'Check position, then involvement, then the defender’s action.'),
  g('Expert','Which statement about defensive transitions is false?',['The nearest player may delay','Central protection buys recovery time','Rest defence starts before possession is lost'],[t('The whole team should attack the regain spot','that can expose the first forward pass'),t('The far-side defender can ignore depth','switches and diagonal runs remain threats'),t('Recovery runs can stop at the ball line','goal-side space may still need protection'),t('Counter-pressing and recovery are the same choice forever','the team may switch from one to the other')],'Delay, protect the centre and rebuild compactness.'),
  g('Expert','Which statement about rest defence is false?',['It supports attacks from behind','It protects likely counter routes','Its shape depends on opponent outlets'],[t('It begins only after losing the ball','the protective structure is built during possession'),t('More attackers always means weaker rest defence','positioning and staggering matter, not only numbers'),t('It should ignore the ball side','where the attack is affects likely regain and counter spaces'),t('The goalkeeper is unrelated','the goalkeeper can protect depth and support circulation')],'Plan the next transition while attacking.'),
  g('Expert','Which statement about third-player combinations is false?',['The first receiver can set the ball','The runner can arrive facing forward','The move can bypass direct pressure'],[t('All three players should stand on one line','angles and different heights make the combination possible'),t('The first passer is always the final receiver','roles can rotate within the action'),t('Timing does not matter','early or late movement can close the route'),t('A third-player action requires a long pass','short combinations can create it')],'Use the player the defender cannot watch at the same time.'),
  g('Expert','Which statement about occupying the box is false?',['Different lanes can stretch defenders','A cut-back target may hold deeper space','Far-post runs can attack blind-side space'],[t('Every attacker should attack the near post','one lane becomes crowded and other spaces disappear'),t('The crosser’s body shape is irrelevant','it gives information about the likely delivery'),t('Late arrivals never score','timed midfield runs often attack free space'),t('Rest defence can be abandoned for every cross','the counter still needs protection')],'Attack different spaces at different times.'),
  g('Expert','Which statement about creating a free player is false?',['An opponent can be attracted away','A rotation can change marking decisions','The goalkeeper can create an overload'],[t('The free player is always nearest the ball','the useful spare may appear on the far side or next line'),t('Numbers alone guarantee access','angles and timing decide whether the pass exists'),t('The free player should wait behind cover','movement must create visibility'),t('The team should ignore the next defender','receiving free is only the first advantage')],'Create, find and release the spare.'),
  g('Expert','Which statement about manipulating a defensive line is false?',['A run behind can force it deeper','A player dropping can pull a marker','Opposite movements can open a lane'],[t('All attackers should make the same run','the defence then solves one picture'),t('Movement matters only if the runner receives','decoy runs can move defenders'),t('The ball carrier need not scan the line','release timing depends on defender and runner'),t('The line’s body shape is irrelevant','open or square defenders manage runs differently')],'Use opposite movements to create a difficult choice.'),
  g('Expert','Which statement about defending the box is false?',['First contact matters','Cut-back zones need protection','Defenders should see ball and likely runner'],[t('Every defender should stand on the goal line','that concedes space for shots and runners'),t('The far post can be left empty','blind-side arrivals are a common threat'),t('Only the centre-backs defend crosses','full-backs, midfielders and goalkeeper share jobs'),t('Second balls are the attack’s problem only','defensive exits and edge protection matter')],'Protect first contact, runners and the next ball.'),
  g('Expert','Which statement about zonal marking is false?',['Players protect assigned spaces','They still react to runners entering the zone','Communication helps pass responsibility'],[t('Players may ignore every opponent','space is the reference, but opponents still create danger'),t('Zonal marking removes all match-ups','specific threats may still be managed'),t('Everyone should attack the same delivery','cover and second-ball roles are also needed'),t('The zone never changes with the ball','the team may adjust its reference as delivery position changes')],'Protect the zone while reading who enters it.'),
  g('Expert','Which statement about man-oriented pressing is false?',['References can limit short options','Players may follow movement within agreed limits','Cover still protects dangerous space'],[t('Every marker should follow anywhere on the pitch','unlimited following can destroy the team shape'),t('The ball carrier can be ignored','pressure on the ball affects every marked option'),t('No player needs cover','duels can be lost and rotations can break references'),t('Switches do not challenge the system','fast changes of side can stretch match-ups')],'Use references without losing the team.'),
  g('Expert','Which statement about a double pivot is false?',['The two midfielders can stagger heights','One can cover while the other moves','Their spacing can help escape pressure'],[t('They should stand side by side in every phase','different heights and angles may be needed'),t('Both should press the same opponent','that can open the space behind'),t('Neither may join attacks','one can advance if balance remains'),t('The partnership removes the need for centre-backs to communicate','the unit still coordinates cover and access')],'Stagger the pair so one move does not remove both.'),
  g('Expert','Which statement about the half-space is false?',['It sits between the centre and wide lane','It can offer useful crossing and passing angles','Players can arrive there from different starting roles'],[t('Only a number ten may enter it','full-backs, eights, wingers and forwards can use it'),t('It is a painted line on the pitch','it is a tactical reference zone'),t('Receiving there guarantees a chance','pressure, body shape and support still matter'),t('Using it means width is unnecessary','outside width can help open the inside lane')],'Combine inside access with outside width.'),
  g('Expert','Which statement about goalkeeper sweeping is false?',['Starting height follows the defensive line','The goalkeeper reads ball pressure','Decision timing balances interception and goal protection'],[t('The goalkeeper should attack every through ball','distance, speed and attacker access can make holding safer'),t('Sweeping is only about pace','reading and timing are crucial'),t('The defensive line need not know the goalkeeper’s position','shared depth management needs communication'),t('A successful sweep must be a sliding tackle','headers, clearances and controlled touches may solve it')],'Read the pass, attacker and goal before committing.'),
  g('Expert','Which statement about set-piece analysis is false?',['Delivery zones should be logged','Blocking and movement patterns matter','Second phases belong in the review'],[t('One goal proves the routine is always good','outcome alone can hide poor repeatability'),t('Only scored corners deserve clips','near chances and failed timing reveal the pattern'),t('Opponent marking is irrelevant','the routine’s value depends on the defence it attacks'),t('The team should copy a routine without adapting roles','execution depends on its own players and opponent')],'Judge repeatable access, not one outcome.'),
  g('Expert','Which statement about recruitment decisions is false?',['Role fit and price both matter','Uncertainty should affect confidence','Alternative views can be recorded'],[t('The highest rating is automatically the best signing','team need, age, cost and fit change the decision'),t('A scout should hide evidence against the recommendation','decision-makers need the full risk picture'),t('Every club should reach the same verdict','models and needs legitimately differ'),t('More data always removes judgement','interpretation remains necessary')],'Make the decision traceable from evidence to need.'),
  g('Expert','Which statement about sample size is false?',['Rare actions may need more matches','Role changes can split the sample','Opponent quality affects interpretation'],[t('Ten clips always equal ten full performances','selected actions are not the same as complete match exposure'),t('A larger sample automatically fixes biased selection','poor sampling can remain poor at scale'),t('One excellent match should outweigh a season','extreme performances need context'),t('Missing minutes can be treated as average minutes','absence is missing evidence, not neutral evidence')],'Ask what the sample includes and what it misses.'),
  g('Expert','Which statement about expected goals is false?',['It estimates chance quality','Different models can produce different values','It does not guarantee an individual shot outcome'],[t('A shot worth 0.30 xG scores 30% of a goal','xG is a probability estimate across comparable chances'),t('The team with more xG must have won','football outcomes can differ from chance quality'),t('All xG models use identical inputs','providers make different modelling choices'),t('xG explains every part of attacking performance','creation, progression and decision context need other evidence')],'Use probability to understand chances, not rewrite the score.'),
]

function buildQuestion(group: TruthGroup, groupIndex: number, variant: number, questionIndex: number): TruthTrapQuestion {
  const trap = group.traps[variant]
  const options = [...group.truths]
  options.splice((groupIndex + variant) % 4, 0, trap.label)
  return {
    id: `trap-${String(questionIndex + 1).padStart(3, '0')}`,
    kind: 'truth-trap',
    difficulty: group.difficulty,
    prompt: group.prompt,
    options,
    answer: trap.label,
    explanation: `${trap.label} is the trap because ${trap.reason}. The other three statements are sound.`,
    takeaway: group.takeaway,
  }
}

export const truthTrapQuestionBank: TruthTrapQuestion[] = Array.from({ length: 4 }, (_, variant) => (
  truthGroups.map((group, groupIndex) => buildQuestion(group, groupIndex, variant, variant * truthGroups.length + groupIndex))
)).flat()
