export type FormationDifficulty='Starter'|'Sharp'|'Expert'
export type FormationVisual='goal'|'left'|'centre'|'right'|'half-space'|'wide'|'depth'
export type FormationQuestion={id:string;kind:'formation-fix';difficulty:FormationDifficulty;visual:FormationVisual;prompt:string;options:string[];answer:string;explanation:string;takeaway:string}
type Fix={difficulty:FormationDifficulty;visual:FormationVisual;problem:string;solution:string;distractors:[string,string,string];explanation:string;takeaway:string}
const f=(difficulty:FormationDifficulty,visual:FormationVisual,problem:string,solution:string,distractors:[string,string,string],explanation:string,takeaway:string):Fix=>({difficulty,visual,problem,solution,distractors,explanation,takeaway})

const fixes:Fix[]=[
  f('Starter','goal','Nobody protects the space straight in front of your centre-backs.','Add a holding midfielder',['Add a second striker','Send both full-backs higher','Move the goalkeeper to the wing'],'A holding midfielder screens central passes and supports regains.','Protect the space before danger reaches the back line.'),
  f('Starter','wide','Your winger moves inside and the opponent full-back can stay narrow.','Add an outside full-back run',['Add another narrow number ten','Drop the striker beside the pivot','Keep the entire flank empty'],'The overlap restores width and makes the defender choose.','If one player comes inside, another can hold outside.'),
  f('Starter','depth','Every midfielder comes short against a high press.','Add a run beyond the last line',['Add another player beside the ball','Slow every pass','Keep every attacker on the halfway line'],'Depth stretches the press and creates room underneath.','Offer options to feet and beyond.'),
  f('Starter','centre','Both full-backs attack and the centre is empty after a loss.','Hold one midfielder behind the attack',['Add another player in the box','Move both centre-backs wide','Ask the striker to take every corner'],'A holding player protects the counter route and supports centre-backs.','Rest defence begins while attacking.'),
  f('Starter','left','Your left-back is isolated two-versus-one.','Recover the left winger or near midfielder',['Send the right winger across first','Move the striker offside','Leave the full-back alone'],'Nearest support helps match the overload while the team shifts.','Solve the nearest overload, then rebalance.'),
  f('Starter','goal','Crosses arrive freely and nobody attacks first contact.','Make the near-side centre-back own first contact',['Keep every defender on the goal line','Ask the far winger to wait at halfway','Move the corner taker into goal'],'A clear first-contact defender attacks the most immediate danger.','Defend first contact before the second ball.'),
  f('Starter','right','The right winger is trapped with no outside or return option.','Give an overlap or safe bounce pass',['Send a second player into the same spot','Remove the nearest midfielder','Ask the left centre-back to dribble across'],'Two exits stop one defender and the touchline becoming a cage.','Give the ball carrier more than one route.'),
  f('Starter','centre','A simple pass keeps finding the opponent midfielder alone during your press.','Screen the central pass',['Press only with the goalkeeper','Keep the back line deep and still','Leave the pivot free on purpose'],'Pressure must connect with cover of the easiest central option.','Press the ball and block the next pass.'),
  f('Starter','depth','You lead late but every attacker drops into your own box.','Keep one forward outlet',['Add a defender on the goal line','Remove every player from midfield','Use a second goalkeeper'],'An outlet can hold or chase clearances and relieve repeated pressure.','Defending a lead still needs a way out.'),
  f('Starter','half-space','The striker drops short and nobody attacks the space behind.','Send an opposite winger or midfielder beyond',['Keep everyone beside the striker','Drop both full-backs into the box','Ask the goalkeeper to become the ten'],'The second runner uses the depth opened by the striker.','One comes short so another goes long.'),
  f('Starter','wide','Your team has the ball but no player gives width on either side.','Hold one player near each outside lane',['Move everyone between the centre-backs','Put both wingers beside the pivot','Ask every player to follow the ball'],'Width stretches the defence and opens central lanes.','Use the full pitch before forcing the middle.'),
  f('Starter','centre','Three midfielders stand on the same horizontal line.','Stagger one midfielder higher or lower',['Bring them even closer together','Remove the deepest passing option','Ask all three to run at the ball'],'Different heights create visible passing angles.','A flat line is easy to cover.'),
  f('Sharp','half-space','A low block protects the middle while winger and striker are both pinned.','Send a number eight into the half-space',['Overlap both centre-backs','Place every midfielder on the touchline','Leave the inside channel empty'],'A timed inside-channel arrival adds a new height and angle.','Arrive in a different lane at a different time.'),
  f('Sharp','centre','The pivot is pressed from behind and both eights stay beyond one cover shadow.','Drop one eight to a new angle',['Keep both eights hidden','Ask the pivot to receive without scanning','Move every option onto the last line'],'A new height can create a third-player route around pressure.','Different heights beat one cover shadow.'),
  f('Sharp','left','The left winger receives wide but the full-back never supports inside or outside.','Give the winger an overlap, underlap or bounce option',['Put another player directly behind the defender','Move the nearest support to the far corner','Ask the winger to beat two players every time'],'A second route changes the defender’s decision.','Support should create a choice, not a crowd.'),
  f('Sharp','centre','The opponent plays through your first press with one pass into the pivot.','Curve the first press and cover the pivot',['Sprint straight and open the lane','Drop the midfield away from pressure','Let the pivot turn freely'],'The pressing angle can pressure ball and remove the central route.','The run should close one option while attacking another.'),
  f('Sharp','depth','Your back line holds high although the passer has time and no pressure.','Drop together to protect depth',['Step higher one by one','Leave the goalkeeper on the goal line','Ignore every run behind'],'Without pressure on the passer, depth becomes the urgent danger.','Line height follows ball pressure.'),
  f('Sharp','goal','The cut-back reaches an unmarked runner at the penalty spot.','Recover a midfielder into the cut-back zone',['Put every defender at the near post','Leave the edge of the box empty','Ask the striker to defend the goal line'],'The midfield recovery protects the space behind the first line.','Defend the delivery and where it is likely to finish.'),
  f('Sharp','wide','The opponent overloads your right side and your far winger stays wide.','Narrow the far-side winger while the block shifts',['Keep the far side disconnected','Send both centre-backs to the ball','Leave the centre completely open'],'Narrowing protects the centre while the team travels.','Far-side players defend before the switch arrives.'),
  f('Sharp','centre','Your number ten and striker both drop into the same pocket.','Keep one between the lines and one on the last line',['Add a third player to the same pocket','Remove all depth','Ask both to follow the pivot'],'Different heights occupy more defenders and preserve depth.','Do not solve one space with two identical movements.'),
  f('Sharp','right','The right full-back overlaps but nobody protects the channel they leave.','Slide the nearest midfielder or centre-back across',['Send the left full-back forward too','Leave the channel unprotected','Ask the winger to stop tracking the ball'],'Cover behind the overlap maintains rest-defence balance.','Every attacking run should have protection behind it.'),
  f('Sharp','left','Your left centre-back steps into midfield and the back line becomes a two-versus-two.','Drop the pivot or narrow the full-back into cover',['Advance the other centre-back as well','Move the goalkeeper to centre-forward','Leave equal numbers with open depth'],'A covering player restores the spare defender.','Replace the protection a stepping defender leaves.'),
  f('Sharp','depth','The opponent centre-backs circulate with no pressure and keep finding long passes.','Move the front line to press or screen the passer',['Drop every forward into your box','Leave both centre-backs free','Ask only the goalkeeper to engage'],'Pressure or screening reduces the quality of long service.','Depth defence begins with the passer.'),
  f('Sharp','centre','Your team wins the ball but the first receiver has no support behind.','Add a safe bounce option',['Send every player forward immediately','Remove the nearest passing angle','Force a blind turn'],'A support pass protects the regain and can launch the next action.','Secure the ball before chasing space.'),
  f('Sharp','wide','The opponent block shifts slowly but your team keeps attacking one crowded side.','Recycle and switch to the far side',['Add another player to the crowd','Stop the ball on the touchline','Remove the far-side winger'],'A switch attacks before the block can reset.','Draw pressure, then use the space it leaves.'),
  f('Sharp','half-space','Your winger holds width but nobody occupies the inside channel.','Move an eight or full-back into the half-space',['Move the winger even wider off the pitch','Put both centre-backs beside the striker','Leave the channel empty'],'Inside support creates a triangle and new passing angle.','Width is strongest when an inside option supports it.'),
  f('Sharp','goal','The striker attacks near post but all other runners follow.','Stagger central, far-post and cut-back runs',['Send everyone to near post','Keep all midfielders at halfway','Ask the crosser to enter the same lane'],'Different target zones stretch box defenders.','Attack several spaces, not one crowd.'),
  f('Sharp','centre','Both pivots jump to press the same receiver.','Keep one pivot covering behind',['Send both centre-backs forward too','Leave the central lane open','Ask the goalkeeper to mark midfield'],'One presses while one protects the space behind.','A pair should not disappear with one jump.'),
  f('Sharp','goal','Your zonal corner defence has three players attacking the same delivery.','Keep one first-contact attacker and preserve cover roles',['Send everyone under the ball','Remove the second-ball player','Leave the far zone empty'],'Clear ownership prevents duplication and protects the next phase.','First contact needs cover and second-ball support.'),
  f('Sharp','right','The right winger presses but the right-back stays deep, opening a large gap.','Squeeze the line behind the press',['Press harder with the winger alone','Drop the midfield farther away','Keep every line disconnected'],'The team must shorten space behind pressure.','A press is only as strong as the support behind it.'),
  f('Sharp','left','The opponent full-back receives facing forward because your winger presses from inside to outside too late.','Start the winger close enough to guide play earlier',['Hide the winger behind the striker','Let the receiver face forward','Move the left-back to the far side'],'A better starting position shapes the pass before it arrives.','The trap begins before the sprint.'),
  f('Sharp','centre','Your team is down to ten and two forwards keep pressing separately.','Use one compact front reference and protect midfield',['Keep both isolated presses','Remove the midfield line','Ask every defender to chase high'],'Compact lines reduce the space the missing player would cover.','With ten, remove wasted distance.'),
  f('Sharp','depth','You are trailing but every attacker comes short.','Add two staggered runs behind',['Bring the centre-backs short too','Remove all last-line threat','Ask the goalkeeper to dribble centrally'],'Depth pins the defence and opens space for short receivers.','Urgency still needs opposite movements.'),
  f('Sharp','centre','You are leading but the midfield keeps chasing wide and opening the centre.','Protect the central lane and show play outside',['Follow every pass anywhere','Leave the pivot unmarked','Send the centre-backs to the touchline'],'Central protection removes the quickest route to goal.','Guide danger away from the centre.'),
  f('Sharp','goal','The goalkeeper cannot claim crosses because two defenders block the route.','Set clear goalkeeper space and defender zones',['Crowd the six-yard box more','Tell nobody to communicate','Ask every defender to attack the goalkeeper’s line'],'Clear starting lanes improve claiming and first-contact decisions.','Protect the goalkeeper’s route as well as the goal.'),
  f('Sharp','centre','The build-up pivot is marked and both full-backs remain hidden behind wingers.','Move one full-back inside or lower to become the spare',['Keep all options behind markers','Force the pivot every time','Send both centre-backs into the box'],'A role change can create the extra player around pressure.','Move someone into the line the press cannot cover.'),
  f('Sharp','wide','The wide player is doubled and the far side is completely free.','Use a secure pass back and switch',['Force the dribble into two defenders','Add a third player beside the ball','Remove the far-side option'],'Recycling keeps the ball and accesses the free side.','Escape the trap before attacking again.'),
  f('Sharp','half-space','The number ten receives between lines but faces their own goal with no third runner.','Add a runner beyond for the set pass',['Ask the ten to turn through two players','Keep every team-mate behind the ball','Move the striker into the same feet space'],'A third runner lets the receiver bounce the ball out of pressure.','Support the receiver’s next action.'),
  f('Sharp','left','Your left-back is high and the opponent winger waits for the counter.','Position a midfielder or centre-back to control that outlet',['Send the covering player into the box','Ignore the winger until possession is lost','Move the goalkeeper to the touchline'],'Rest defence should mark space and counter outlets before the loss.','Protect the likely first counter pass.'),
  f('Sharp','right','The opponent right winger keeps arriving blind side at your far post.','Narrow the left-back early and track the runner',['Watch only the ball','Keep the left-back outside the penalty area','Ask the near centre-back to leave first contact'],'Far-side defenders must see ball and runner.','Back-post danger begins away from the ball.'),
  f('Sharp','centre','Your midfield block is compact but the striker never screens the opponent pivot.','Adjust the striker’s pressing lane to block the pivot',['Drop the midfield away','Leave the pivot as the free player','Press the goalkeeper from a straight line'],'The first line can guide play and protect the centre together.','Use the cover shadow with purpose.'),
  f('Sharp','depth','A quick striker repeatedly starts behind your high line.','Give the goalkeeper a higher sweeping position',['Keep the goalkeeper fixed on the line','Push one defender higher alone','Ignore pass speed and pressure'],'A suitable starting height shares depth control with defenders.','Goalkeeper and line defend the space together.'),
  f('Sharp','goal','Second balls from corners keep falling to an opponent at the edge.','Assign an edge defender or midfielder',['Send every player under the cross','Leave the edge unoccupied','Ask the corner taker to defend it'],'The edge role protects rebounds and starts exits.','Set pieces continue after first contact.'),
  f('Sharp','wide','The opponent has no wide player but your full-back remains pinned deep.','Release the full-back to support higher while cover shifts',['Keep unnecessary five-player depth','Remove all midfield protection','Send both centre-backs to overlap'],'Recognising the free defender can create an overload.','Use the spare player the opponent gives you.'),
  f('Expert','centre','A man-oriented press is being dragged apart by crossing midfield rotations.','Pass references while protecting the central space',['Follow every runner anywhere','Keep silent and hope markers recover','Abandon the centre to preserve match-ups'],'Reference exchanges stop rotations pulling the team apart.','Protect the threat, not the name on the shirt.'),
  f('Expert','half-space','The opponent full-back moves inside and creates a midfield overload.','Narrow the winger or release a midfielder to match it',['Keep every wide player outside','Send a centre-back to the touchline','Ignore the spare until the box'],'The nearest line must recognise and balance the new inside player.','Track role changes, not starting formations.'),
  f('Expert','centre','Your double pivot is covered by one curved pressing run.','Stagger the pivots and use a third-player route',['Keep both on the same line','Pass directly through the cover shadow','Move both pivots behind the same marker'],'Different heights make one cover shadow insufficient.','Stagger before asking for the pass.'),
  f('Expert','depth','The false nine drops and your centre-back follows, opening a channel behind.','Pass the short player to midfield and protect depth',['Follow into midfield every time','Step both centre-backs together without cover','Ask the full-back to ignore the inside run'],'Shared references prevent one movement opening the last line.','Do not trade the goal-side space for a harmless touch.'),
  f('Expert','half-space','Your winger receives inside but the outside lane is empty and the defence collapses.','Hold the full-back or opposite rotation wide',['Move the full-back into the same pocket','Remove the only width','Ask the striker to join the crowd'],'Outside width fixes a defender and preserves the inside receiver’s space.','Inside access needs outside support.'),
  f('Expert','centre','The opponent blocks your pivot and presses centre-backs two-versus-two.','Drop an eight or use the goalkeeper to create a three-versus-two',['Keep every midfielder beyond pressure','Force the marked pivot','Remove the goalkeeper from build-up'],'An extra first-line player creates the spare route.','Change the numbers around the press.'),
  f('Expert','wide','The opponent leaves the far full-back free but your switch is too slow.','Prepare the next pass before the switch arrives',['Let the receiver wait flat-footed','Add more passes on the crowded side','Hide the far winger behind the same defender'],'Pre-orientation lets the free player attack before the block travels.','The switch is only useful if the next action is ready.'),
  f('Expert','goal','Your near centre-back attacks the cross and the other also follows the ball.','Keep the far centre-back protecting central and far-post depth',['Send both to first contact','Leave the striker untracked','Move the full-back to the near-post crowd'],'Cover behind first contact protects the next delivery lane.','One attacks; one protects what happens next.'),
  f('Expert','centre','Your counter-press wins first contact but nobody secures the next pass.','Place a supporting player behind the first press',['Commit every player beyond the ball','Remove the safe receiver','Treat the regain as finished instantly'],'The support player turns a loose regain into controlled possession.','Winning it and keeping it are two actions.'),
  f('Expert','depth','Your counter-press is broken but players keep chasing forward.','Call the recovery and sprint goal-side',['Continue isolated pressure forever','Leave centre-backs equal in open space','Ask the goalkeeper to press midfield'],'Once access is lost, recovery protects the goal.','Know when the press has ended.'),
  f('Expert','half-space','The opponent overloads one half-space with winger, eight and dropping striker.','Create a compact triangle of full-back, centre-back and midfielder',['Defend each player with no cover','Send the far centre-back into the crowd','Leave the inside lane open'],'A compact triangle shares pressure and cover across the overload.','Match an overload with connected roles.'),
  f('Expert','centre','The opponent’s number ten floats behind your pivot and in front of centre-backs.','Set a clear handover between pivot and centre-back',['Let both assume the other will mark','Follow the ten with the striker','Drop the entire midfield to the goal line'],'A handover protects the pocket without dragging one line apart.','Communicate who owns the player and when.'),
  f('Expert','goal','Your zonal corner line protects space but ignores a late runner entering the zone.','Track the runner once they enter the dangerous zone',['Watch space without opponents','Abandon every zone to man-mark','Send all defenders to the taker'],'The zone is a starting reference, not permission to ignore danger.','Protect space and react to who enters it.'),
  f('Expert','wide','Your overload draws four defenders but the team never switches.','Find the free far-side player',['Add a fifth player to the overload','Force a pass through four defenders','Remove the far-side width'],'The overload’s reward may be the underloaded far side.','Attract pressure, then leave it.'),
  f('Expert','centre','The number six drops between centre-backs and both full-backs also stay deep.','Release one full-back or midfielder into the next line',['Keep six players behind first pressure','Remove every between-lines option','Ask the striker to build alone'],'Too many players behind the ball can leave no progression target.','Secure build-up without emptying the next line.'),
  f('Expert','depth','The opponent holds a high line but your runners go too early and are repeatedly offside.','Delay the run until the passer can release',['Start even earlier','Stop threatening depth completely','Ask the passer to release before controlling'],'Timing connects the runner’s movement with ball-carrier access.','Run when the pass can be played.'),
]

const permutations=[[0,2,1,3],[2,0,3,1],[1,3,0,2],[3,1,2,0]] as const
const frames=['You spot this problem: ','Freeze the match: ','Coach’s view: ','Next action: '] as const
const questions=[' Which fix is best?',' What should the team add?',' Which adjustment repairs it?',' What is the clearest solution?'] as const
function buildQuestion(fix:Fix,index:number,variant:number,questionIndex:number):FormationQuestion{
  const choices=[fix.solution,...fix.distractors]
  return {id:`shape-${String(questionIndex+1).padStart(3,'0')}`,kind:'formation-fix',difficulty:fix.difficulty,visual:fix.visual,prompt:`${frames[variant]}${fix.problem}${questions[variant]}`,options:permutations[(index+variant)%4].map(choice=>choices[choice]),answer:fix.solution,explanation:fix.explanation,takeaway:fix.takeaway}
}
export const formationFixQuestionBank:FormationQuestion[]=Array.from({length:4},(_,variant)=>fixes.map((fix,index)=>buildQuestion(fix,index,variant,variant*fixes.length+index))).flat()
