export type OrderDifficulty = 'Starter' | 'Sharp' | 'Expert'
export type OrderQuestion = { id: string; kind: 'order-the-play'; difficulty: OrderDifficulty; prompt: string; items: string[]; answer: string[]; explanation: string; takeaway: string }
type Sequence = { difficulty: OrderDifficulty; prompt: string; steps: [string,string,string,string]; explanation: string; takeaway: string }
const s = (difficulty: OrderDifficulty, prompt: string, steps: [string,string,string,string], explanation: string, takeaway: string): Sequence => ({ difficulty, prompt, steps, explanation, takeaway })

const sequences: Sequence[] = [
  s('Starter','Build the referee’s clean decision sequence.',['Observe the action','Identify any offence','Choose any discipline','Set the restart'],'Observation comes before the offence, sanction and restart.','See it → name it → sanction it → restart.'),
  s('Starter','Put a simple pass into the right learning order.',['Scan before the ball arrives','Move into a visible lane','Receive with a useful body shape','Play the next action'],'Information and movement prepare the touch and pass.','See → show → receive → play.'),
  s('Starter','Order the first four actions after winning the ball.',['Secure the first touch','Scan for pressure and runners','Choose pass or carry','Attack the available space'],'Control and information come before the release.','Win it, see it, choose it, attack it.'),
  s('Starter','Order a safe training session opening.',['Check the session goal','Complete the warm-up','Start the first focused drill','Raise intensity gradually'],'Purpose and preparation should come before hard work.','Know the aim, prepare, then build.'),
  s('Starter','Put a fair quiz attempt in order.',['Read the full question','Read every option','Choose the best answer','Read the explanation'],'Careful reading comes before the choice, and feedback completes the loop.','Question → choices → answer → why.'),
  s('Starter','Order the way to compare two players fairly.',['Note each match context','Match the role and level','Collect enough actions','Make the judgement'],'Context and comparable evidence make the verdict useful.','Compare like with like.'),
  s('Starter','Order a throw-in from decision to restart.',['See the ball cross the touchline','Identify the last touch','Point to the correct team','Allow a legal throw-in'],'The line and last touch determine direction before the throw.','Line first, last touch second.'),
  s('Starter','Order a player’s response after making a mistake.',['Recognise what happened','React to the next danger','Reset the position','Review the lesson later'],'Live play needs recovery before reflection.','Recover now; review later.'),
  s('Starter','Order a simple shooting decision.',['Scan the goal and pressure','Set the ball if needed','Choose power or placement','Strike through the chosen line'],'The finish should follow the picture.','See the chance before choosing the finish.'),
  s('Starter','Order a clean team-mate instruction.',['Notice the useful information','Call the player’s name','Give one short message','Confirm the next action'],'Short, early information is easiest to use.','Notice → name → message → action.'),
  s('Starter','Order a basic goal-kick plan.',['Spread into the agreed shape','Find the free first pass','Draw the first presser','Use the open route'],'Shape creates choices before the team moves pressure.','Shape, find, draw, escape.'),
  s('Starter','Order a safe return after a minor knock.',['Tell the responsible adult or staff','Get the issue assessed','Follow the recovery plan','Return through agreed steps'],'Assessment should guide recovery and return.','Report, assess, recover, return.'),
  s('Sharp','Put a scouting report into a sensible order.',['Record the observation','Explain what it may mean','State what is still unknown','Make the recommendation'],'Observation must stay separate from interpretation and action.','Evidence first; judgement last.'),
  s('Sharp','Order a coordinated high-press trap.',['Show play toward the chosen side','Jump on the shared trigger','Close the nearest exits','Squeeze the team behind the press'],'The trap guides the ball before pressure and cover arrive together.','Show, jump, close, squeeze.'),
  s('Sharp','Order the escape from a high press.',['Create width and depth','Find the spare player','Move the ball to draw pressure','Play through or around the free route'],'The team creates, identifies and accesses the advantage.','Shape → scan → draw → escape.'),
  s('Sharp','Order a response to losing the ball in midfield.',['Nearest player delays the attack','Protect the central route','Choose counter-press or recovery','Regain compact team spacing'],'Delay buys time for protection and the team decision.','Delay, protect, decide, recover.'),
  s('Sharp','Order a safe substitution process.',['Diagnose the match problem','Choose the profile that solves it','Explain the new role','Review the effect'],'The change should answer a clear problem and be checked afterwards.','Problem → profile → role → review.'),
  s('Sharp','Order a corner routine before first contact.',['Confirm every role','Check counter-attack cover','Start movement on the cue','Attack the assigned zones'],'Roles and protection must be ready before delivery and runs.','Clarity before movement.'),
  s('Sharp','Order a quick counter-attack through three lanes.',['Secure the regain','Release the ball carrier','Fill separate running lanes','Choose the final pass or shot'],'The team first protects the regain, then creates and uses space.','Secure, release, spread, finish.'),
  s('Sharp','Order an overlap on the right.',['Winger receives and holds the defender','Right-back starts the outside run','Ball is released into the outside lane','Box runners attack the delivery'],'The ball carrier fixes the defender before the runner is released.','Fix, run, release, arrive.'),
  s('Sharp','Order a third-player combination.',['First player passes into support','Receiver sets the ball away from pressure','Third player arrives facing forward','Attack continues beyond the line'],'The set releases a player the defender cannot watch at once.','Pass, set, arrive, break.'),
  s('Sharp','Order a switch of play against a narrow block.',['Draw defenders toward one side','Secure a backwards or inside pass','Find the free far-side player','Attack before the block shifts'],'Drawing pressure creates the far-side opening.','Draw, secure, switch, attack.'),
  s('Sharp','Order a low-block attack using a cut-back.',['Hold width to stretch the block','Create an outside or inside release','Reach the space beside the box','Find the late runner behind the midfield line'],'Width and penetration create the cut-back lane and target.','Stretch, release, reach, cut back.'),
  s('Sharp','Order a striker’s pressing action.',['Check the centre-back’s options','Curve the run to block one pass','Apply pressure to the ball','Team-mates jump to the next options'],'The curved run begins a connected press rather than a solo chase.','See, curve, press, connect.'),
  s('Sharp','Order a back-line response to a ball in behind.',['Read pressure on the passer','Drop or hold as one line','Goalkeeper adjusts starting position','Defend the pass and second action'],'Passer pressure and shared depth decide the line.','Read the ball, move together.'),
  s('Sharp','Order the defence of a wide overload.',['Nearest defender delays the carrier','Wide support recovers','Inside defenders protect central runners','Team shifts and regains balance'],'Delay allows support and central protection to arrive.','Delay, support, protect, rebalance.'),
  s('Sharp','Order a goalkeeper’s build-up decision.',['Scan the opponent’s first line','Set the team’s spacing','Choose short, through or over','Deliver with the right weight'],'Information and structure come before distribution.','Scan, shape, choose, deliver.'),
  s('Sharp','Order a goalkeeper sweep.',['Read the through-ball speed','Compare attacker and defender access','Choose hold, claim or clear','Recover the goal or support the next pass'],'The keeper judges access before committing and then resets.','Read access before leaving goal.'),
  s('Sharp','Order a centre-back stepping into midfield.',['See the receiver between lines','Check cover behind','Step as the pass travels','Win, delay or force play away'],'Cover makes the aggressive step safer.','See, secure cover, step, solve.'),
  s('Sharp','Order a midfielder receiving on the half-turn.',['Scan both shoulders','Move off the marker’s cover','Open the body as the pass travels','Play forward or protect the ball'],'Early information and movement create the forward action.','Scan, show, open, act.'),
  s('Sharp','Order a winger’s one-versus-one attack.',['Receive with space to face forward','Read the defender’s stance','Use the first action to unbalance','Cross, pass or shoot after separation'],'The final action follows the defender’s reaction.','Face, read, move, release.'),
  s('Sharp','Order a striker’s run across a centre-back.',['Start outside the defender’s sight','Wait for ball-carrier control','Accelerate across the defender','Finish or set the next action'],'Blind-side position and release timing create the advantage.','Hide, wait, cross, finish.'),
  s('Sharp','Order a set-piece video review.',['Define the question','Collect every relevant delivery','Code runs, zones and outcomes','Share one actionable pattern'],'A focused question leads to complete evidence and a usable answer.','Question, evidence, pattern, action.'),
  s('Sharp','Order a match-analysis workflow.',['Define the team problem','Gather clips and context','Test repeat patterns and alternatives','Present the clearest action'],'Analysis moves from a question to evidence and a decision.','Do not start with the conclusion.'),
  s('Sharp','Order a recruitment meeting decision.',['State the squad need','Present evidence and uncertainty','Compare fit, cost and alternatives','Agree the next action'],'The need frames the evidence before trade-offs and action.','Need → evidence → options → action.'),
  s('Sharp','Order a youth-player follow-up.',['Record the current context','Identify one promising repeatable trait','Name the missing evidence','Plan the next observation'],'Projection stays honest when strengths and unknowns are both recorded.','See the trait and plan the proof.'),
  s('Sharp','Order a fair data comparison.',['Choose the football question','Define the same role and opportunity','Calculate the relevant rate or trend','Check the result against match context'],'The metric belongs after the question and fair denominator.','Question before number.'),
  s('Sharp','Order a late-game plan while leading.',['Read the opponent’s added risk','Protect central counter routes','Keep one useful outlet','Use safe possession when available'],'The team controls threat, escape and ball.','Protect, escape, keep.'),
  s('Sharp','Order a late-game plan while trailing.',['Identify where the opponent is protecting','Add a useful attacking occupation','Move the ball before the block settles','Protect the counter behind the attack'],'Extra threat should target the block without removing all security.','Add threat with a reason.'),
  s('Sharp','Order a team reset after the press is broken.',['Nearest player slows the attack','Midfield protects the centre','Back line controls depth','Team reconnects into a compact block'],'Each line buys time for the next until the team reconnects.','Slow, protect, control, reconnect.'),
  s('Sharp','Order the response to a possible head injury.',['Notice the signs and player reaction','Stop play for serious concern','Allow medical assessment','Restart only when safe and correct'],'Recognition and safety come before match flow.','Notice, stop, assess, restart.'),
  s('Sharp','Order an advantage decision.',['Recognise the foul','Check the immediate attacking benefit','Signal and monitor the next seconds','Return to misconduct at the stoppage if needed'],'The referee compares continuation with the free kick, then manages consequences.','Foul, benefit, signal, manage.'),
  s('Sharp','Order an offside judgement.',['Freeze the attacker’s position at the team-mate’s touch','Check whether the player becomes involved','Judge any defender action','Signal only when the offence is complete'],'Position comes before involvement and any reset question.','Position → involvement → defender → decision.'),
  s('Sharp','Order a disciplinary decision after a challenge.',['See the nature of contact','Judge careless, reckless or excessive force','Choose the required card','Manage the correct restart'],'Severity determines discipline while the offence determines the restart.','Nature, severity, card, restart.'),
  s('Expert','Order a rest-defence setup during an attack.',['Identify opponent counter outlets','Position protection behind the ball','Stagger cover around the attack','Adjust as the ball changes side'],'The protective shape is built before possession is lost.','Plan the transition while attacking.'),
  s('Expert','Order a man-oriented press against a rotation.',['Recognise the opponent’s movement','Pass or adjust the marking reference','Protect the dangerous space','Press when the new receiver is controlled'],'References can change without abandoning the team’s key space.','Track the threat, not movement for its own sake.'),
  s('Expert','Order a double-pivot rotation under pressure.',['One pivot attracts the marker','The partner moves to a new height','A defender finds the free angle','The receiving pivot releases the next line'],'Staggering the pair creates a new passing lane.','Move one marker, free the partner.'),
  s('Expert','Order an underlap into the half-space.',['Wide player holds the full-back','Inside runner starts from a deeper blind side','Ball carrier waits for the lane','Runner receives or creates space for the outside option'],'Width fixes the defender before the inside route opens.','Hold outside to release inside.'),
  s('Expert','Order a false-nine rotation.',['Centre-forward drops between lines','Centre-back decides whether to follow','Wide or midfield runner attacks the opened depth','Ball carrier finds the free player or decoy space'],'Opposite movements make the defender choose.','One comes short; another goes long.'),
  s('Expert','Order the defence of a cut-back.',['Wide defender slows the entry','Near defender protects the goal-side lane','Midfielder tracks the cut-back zone','Far defender controls the back-post runner'],'The defence protects delivery, central finish and far-side threat together.','Defend the cross and the spaces it targets.'),
  s('Expert','Order a zonal corner defence.',['Set each player’s starting zone','Identify the most dangerous movement','Attack the delivery within the zone','Push out and defend the second ball'],'Zonal reference still requires reading runners and the next action.','Zone, read, attack, reset.'),
  s('Expert','Order a counter-press that must become recovery.',['Attack the first pass after the loss','Close the most dangerous short exit','Recognise the opponent has escaped','Sprint goal-side into the recovery shape'],'The team presses early but changes plan once access is lost.','Press together; recover together.'),
  s('Expert','Order a video review of a goalkeeper error.',['Describe the full starting picture','Separate decision from execution','Compare alternative actions','Set one training objective'],'A mistake becomes useful when its cause and alternative are clear.','Explain the choice before judging the outcome.'),
  s('Expert','Order a multi-match scouting conclusion.',['Code repeatable actions by context','Compare different opponents and roles','Test the strongest alternative view','Set confidence and recommendation'],'A robust conclusion survives varied samples and challenge.','Repeat, compare, challenge, decide.'),
  s('Expert','Order an expected-goals review.',['Define which chances are included','Compare chance quality and game state','Watch how the chances were created','State what xG can and cannot prove'],'The number needs scope, context, video and limits.','Probability explains chances, not destiny.'),
  s('Expert','Order the diagnosis of a possession problem.',['Locate where possession stops progressing','Identify pressure, spacing and available routes','Test whether the pattern repeats','Choose one structural or decision fix'],'The analyst finds the bottleneck before prescribing a fix.','Locate, explain, test, fix.'),
  s('Expert','Order a tournament tie-break check.',['Open the published competition rules','Confirm the relevant table and results','Apply criteria in the written order','Record and communicate the outcome'],'Tie-breaks must follow the competition’s own stated sequence.','Use the rulebook, not memory.'),
  s('Expert','Order a VAR-style review principle.',['Identify the on-field decision','Check the available incident evidence','Apply the competition review threshold','Communicate the final decision clearly'],'Review begins with the decision and uses the stated threshold.','Decision, evidence, threshold, outcome.'),
  s('Expert','Order a return-to-play judgement.',['Review medical guidance and symptoms','Complete the agreed progression','Check the player response at each stage','Clear full return only when criteria are met'],'Progression and response come before full clearance.','Health criteria decide the return.'),
  s('Expert','Order a season-long player development review.',['Compare the starting objective with evidence','Separate growth from changing opportunity','Identify the next limiting skill','Set the next measurable focus'],'The review connects goal, context, bottleneck and next action.','Measure growth, then choose the next target.'),
]

const permutations = [[2,0,3,1],[1,3,0,2],[3,1,2,0],[0,2,1,3]] as const
const framings = ['','Reset the picture: ','Mastery check: ','Final sequence: '] as const

function buildQuestion(sequence: Sequence, sequenceIndex: number, variant: number, questionIndex: number): OrderQuestion {
  return {
    id: `order-${String(questionIndex + 1).padStart(3,'0')}`,
    kind: 'order-the-play',
    difficulty: sequence.difficulty,
    prompt: `${framings[variant]}${sequence.prompt}`,
    items: permutations[(sequenceIndex + variant) % permutations.length].map((index) => sequence.steps[index]),
    answer: [...sequence.steps],
    explanation: sequence.explanation,
    takeaway: sequence.takeaway,
  }
}

export const orderThePlayQuestionBank: OrderQuestion[] = Array.from({ length: 4 }, (_, variant) => (
  sequences.map((sequence, sequenceIndex) => buildQuestion(sequence, sequenceIndex, variant, variant * sequences.length + sequenceIndex))
)).flat()
