export type LinkDifficulty = 'Starter' | 'Sharp' | 'Expert'
export type LinkQuestion = { id:string; kind:'link-up'; difficulty:LinkDifficulty; prompt:string; pairs:Array<{left:string;right:string}>; rightOptions:string[]; explanation:string; takeaway:string }
type Board = { difficulty:LinkDifficulty; prompt:string; pairs:[string,string][]; explanation:string; takeaway:string }
const b=(difficulty:LinkDifficulty,prompt:string,pairs:[string,string][],explanation:string,takeaway:string):Board=>({difficulty,prompt,pairs,explanation,takeaway})

const boards: Board[] = [
  b('Starter','Match each role to its main reference point.',[['Goalkeeper','Goal and penalty area'],['Centre-back','Last defensive line'],['Number six','Space in front of defence'],['Centre-forward','Highest attacking line']],'Each role starts from a different line or space.','Know the home position before reading movement.'),
  b('Starter','Match each restart to the event that normally creates it.',[['Throw-in','Ball crosses the touchline'],['Goal kick','Attacker last touches over goal line'],['Corner kick','Defender last touches over goal line'],['Kick-off','A half begins or a goal follows']],'Boundary and last touch decide these restarts.','Line first; last touch second.'),
  b('Starter','Match each pitch line to its job.',[['Touchline','Side boundary'],['Goal line','End boundary'],['Halfway line','Splits the two halves'],['Penalty-area line','Marks the main goalkeeper-handling area']],'Pitch markings give players and officials shared references.','Name the line before using the rule.'),
  b('Starter','Match each basic action to its purpose.',[['Pass','Move the ball to a team-mate'],['Carry','Travel with the ball'],['Shoot','Try to score'],['Clear','Remove immediate danger']],'The action label describes its main intention.','Purpose helps explain the choice.'),
  b('Starter','Match each position to a common shirt-number tradition.',[['Goalkeeper','1'],['Right-back','2'],['Centre-forward','9'],['Playmaker','10']],'Numbers are traditions, not fixed Laws or roles.','Use number traditions as clues, never proof.'),
  b('Starter','Match each communication call to the information it gives.',[['Time','No immediate pressure'],['Man on','Pressure is arriving'],['Turn','Space is available forward'],['Hold','Keep the current position or ball']],'Short calls can prepare a player before the ball arrives.','Early, short and useful wins.'),
  b('Starter','Match each training habit to its benefit.',[['Warm-up','Prepares body and mind'],['Hydration','Supports fluid balance'],['Sleep','Supports recovery'],['Cool-down review','Closes the learning loop']],'Preparation and recovery protect the quality of practice.','Training includes what happens around the drill.'),
  b('Starter','Match each quiz habit to its benefit.',[['Read every option','Avoid a rushed trap'],['Read the explanation','Learn why'],['Replay later','Practise recall'],['Try a harder round','Add useful difficulty']],'Good quiz habits turn scores into learning.','Answer, understand, revisit.'),
  b('Starter','Match each country to its top-flight league.',[['England','Premier League'],['Spain','La Liga'],['France','Ligue 1'],['Germany','Bundesliga']],'These are the named top national divisions.','League names are useful country clues.'),
  b('Starter','Match each tournament to its usual team type.',[['FIFA World Cup','Senior national teams'],['UEFA Champions League','European clubs'],['Africa Cup of Nations','African national teams'],['Copa Libertadores','South American clubs']],'Competitions differ by geography and club or country status.','Check who competes before comparing tournaments.'),
  b('Starter','Match each scoreline phrase to its meaning.',[['Level','Scores are equal'],['Leading','Team has more goals'],['Trailing','Team has fewer goals'],['Clean sheet','Team conceded no goals']],'Simple match language describes the current or final score.','Read the score before judging risk.'),
  b('Starter','Match each card to its consequence.',[['Yellow card','Caution'],['Second yellow','Sending-off after second caution'],['Red card','Sending-off'],['No card','No disciplinary sanction']],'Cards describe disciplinary action, separate from the restart.','Foul, card and restart are separate questions.'),
  b('Sharp','Match each foul-severity word to its meaning.',[['Careless','Foul without automatic card'],['Reckless','Caution required'],['Excessive force','Sending-off required'],['Fair challenge','No foul solely for contact']],'The exact severity word changes discipline.','Contact alone is not the decision.'),
  b('Sharp','Match each scouting section to the question it answers.',[['Observation','What happened?'],['Interpretation','What might it mean?'],['Missing evidence','What do we still need?'],['Recommendation','What should the club do next?']],'A clear report separates evidence, meaning, uncertainty and action.','Do not hide opinion inside observation.'),
  b('Sharp','Match each pressing action to its job.',[['First press','Force the next pass'],['Cover shadow','Block a lane while pressing'],['Squeeze up','Reduce space behind pressure'],['Recovery run','Protect goal-side space']],'Pressing works through connected jobs.','Pressure, block, squeeze, recover.'),
  b('Sharp','Match each pressing trigger to why it helps.',[['Poor first touch','Receiver loses control time'],['Slow back pass','Ball travels toward pressure'],['Pass to touchline','Boundary removes one escape side'],['Bouncing ball','Receiver needs extra control']],'Triggers are moments when the receiver has fewer options or less time.','Jump when control becomes difficult.'),
  b('Sharp','Match each attacking movement to the space it uses.',[['Overlap','Outside the ball carrier'],['Underlap','Inside the ball carrier'],['Run in behind','Beyond the last line'],['Drop short','In front of the last line']],'Movement names describe routes relative to team-mates or defenders.','Different routes move different defenders.'),
  b('Sharp','Match each receiving habit to its benefit.',[['Scan early','See pressure and options'],['Move off cover','Become visible to the passer'],['Open body shape','Access more of the pitch'],['First touch away from pressure','Protect the next action']],'The receiving action begins before the ball arrives.','Information creates time.'),
  b('Sharp','Match each pass type to its common purpose.',[['Bounce pass','Return the ball around pressure'],['Switch','Change the point of attack'],['Through ball','Release a runner beyond'],['Cut-back','Find a runner behind the first line']],'Pass types solve different spaces and pressure pictures.','Name the purpose, not only the technique.'),
  b('Sharp','Match each transition job to its priority.',[['Nearest defender','Delay the ball'],['Holding midfielder','Protect the centre'],['Far-side defender','Control depth and switch'],['Goalkeeper','Protect space behind the line']],'A transition is safer when each player protects a different danger.','Delay buys the team time to reconnect.'),
  b('Sharp','Match each build-up role to its contribution.',[['Goalkeeper','Create an extra first-line option'],['Centre-back','Carry or pass through first pressure'],['Pivot','Connect the next line'],['Full-back','Provide width or move inside']],'Build-up shape creates multiple routes.','Find the free role before forcing the pass.'),
  b('Sharp','Match each low-block solution to the problem it targets.',[['Switch of play','Narrow defence'],['Underlap','Gap inside the full-back'],['Cut-back','Space behind midfield line'],['Run in behind','Defence stepping too high']],'Different tools attack different defensive behaviours.','Choose the solution the block gives you.'),
  b('Sharp','Match each box run to its target zone.',[['Near-post run','Space in front of first defender'],['Central run','Main scoring lane'],['Far-post run','Blind-side space'],['Late edge run','Cut-back zone']],'Staggered runs occupy different finishing spaces.','Do not send every runner to one point.'),
  b('Sharp','Match each defensive body shape to its purpose.',[['Side-on stance','See ball and runner'],['Goal-side position','Protect route to goal'],['Low balanced stance','React in one-versus-one'],['Open midfield stance','Receive and play forward']],'Body shape makes information and movement easier.','Prepare the body for the next danger.'),
  b('Sharp','Match each centre-back action to its support need.',[['Step into receiver','Cover behind'],['Attack aerial ball','Protection for second ball'],['Carry into midfield','Balance behind the ball'],['Hold the line','Pressure on the passer']],'Aggressive actions are safer with connected cover.','Check who protects the space you leave.'),
  b('Sharp','Match each goalkeeper action to its key cue.',[['Sweep','Access to a ball in behind'],['Claim cross','Flight, traffic and reach'],['Short pass','Press and free receiver'],['Long distribution','Target and second-ball shape']],'Goalkeeper decisions use ball, space, pressure and team shape.','Read access before committing.'),
  b('Sharp','Match each game state to its clearest priority.',[['Leading late','Control central risk and keep outlet'],['Trailing late','Add useful attacking threat'],['Level and controlling','Attack with rest defence'],['Down to ten','Stay compact and choose pressure']],'Score, time and player numbers change risk.','The same shape can need a different priority.'),
  b('Sharp','Match each set-piece role to its job.',[['Taker','Deliver on the cue'],['Screen runner','Delay a marker legally'],['Primary attacker','Attack the chosen zone'],['Rest-defence player','Protect the counter']],'A routine needs delivery, movement, finish and protection.','Everyone should know the job before the cue.'),
  b('Sharp','Match each evidence problem to the safer response.',[['One match watched','Collect a larger sample'],['Role changed','Separate evidence by role'],['Weak opponent','Test matched opposition'],['Return from injury','Record return-to-play context']],'The next observation should directly reduce uncertainty.','Name the gap, then plan the evidence.'),
  b('Sharp','Match each data term to its plain meaning.',[['Total','How many happened'],['Rate','How often per opportunity'],['Trend','How the number changes over time'],['Percentile','Position relative to a comparison group']],'Different summaries answer different questions.','Pick the number that matches the question.'),
  b('Sharp','Match each chance clue to what it changes.',[['Distance','Typical scoring difficulty'],['Angle','Available goal width'],['Pressure','Time and execution difficulty'],['Assist type','How the chance arrived']],'Chance context affects how a shot should be read.','A shot is more than its final location.'),
  b('Sharp','Match each winger clue to the skill it shows.',[['Beats full-back','One-versus-one threat'],['Holds touchline','Width discipline'],['Arrives far post','Off-ball scoring threat'],['Recovers after loss','Transition responsibility']],'A winger contributes in several phases.','Judge action and movement.'),
  b('Sharp','Match each striker clue to the skill it shows.',[['Pins centre-back','Line occupation'],['Drops to set pass','Link play'],['Runs across defender','Depth timing'],['Curves first press','Defensive direction']],'Strikers affect space, connection and pressure as well as shots.','Watch what the striker makes possible.'),
  b('Sharp','Match each midfielder clue to the skill it shows.',[['Scans twice','Information gathering'],['Breaks a line','Progression'],['Supports behind ball','Possession security'],['Protects counter route','Rest defence']],'Midfield value appears before, during and after possession.','Read the next action and the safety behind it.'),
  b('Sharp','Match each full-back clue to the role it shows.',[['Overlaps winger','Outside support'],['Moves into midfield','Inverted support'],['Tracks far-post runner','Back-post defence'],['Delays wide counter','Transition defence']],'Full-backs can solve wide and central tasks.','Judge the role in its team structure.'),
  b('Sharp','Match each leadership action to its value.',[['Organise early','Prevent confusion'],['Own a mistake','Model accountability'],['Praise recovery','Support resilience'],['Ask a clear question','Improve shared understanding']],'Leadership can be quiet, practical and repeatable.','Useful leadership clarifies the next action.'),
  b('Sharp','Match each mini-league setting to what it controls.',[['Join code','Who can enter'],['Scoring rule','How points are earned'],['Time window','When entries close'],['Visibility','Who can see results']],'Clear settings protect trust and make competition easy to understand.','Set the rules before inviting players.'),
  b('Sharp','Match each offside idea to its example.',[['Position only','No involvement in play'],['Interfering with play','Touches team-mate’s pass'],['Interfering with opponent','Blocks goalkeeper’s view'],['Gaining advantage','Plays rebound from post']],'Position is penalised only when the player becomes involved in a defined way.','Check position, then involvement.'),
  b('Sharp','Match each advantage clue to what it suggests.',[['Open attack continues','Possible real benefit'],['Player immediately loses ball','Little or no benefit'],['Promising space ahead','Reason to delay whistle'],['Serious injury concern','Reason to stop despite flow']],'Advantage compares immediate football benefit with the free kick and safety.','Possession alone is not enough.'),
  b('Sharp','Match each disciplinary label to an example.',[['Careless','Mistimed trip without recklessness'],['Reckless','Challenge disregarding danger'],['Serious foul play','Excessive force challenging for ball'],['Violent conduct','Brutality outside a normal ball challenge']],'The nature of the action guides discipline.','Use the exact category.'),
  b('Sharp','Match each handball clue to why it matters.',[['Arm movement','May show action toward ball'],['Arm position','May make body unnaturally bigger'],['Ball distance','Affects reaction opportunity'],['Scorer’s immediate contact','Has specific goal consequence']],'Handball decisions require several factual observations.','Contact starts the check; criteria finish it.'),
  b('Sharp','Match each substitution step to its question.',[['Diagnose','What is going wrong?'],['Select profile','Who solves that problem?'],['Brief role','What exactly should change?'],['Review','Did the change work?']],'A substitution is a decision cycle, not just a player swap.','Problem before player.'),
  b('Sharp','Match each review habit to its protection against bias.',[['Include failed actions','Avoid success-only selection'],['Note opposition','Keep context'],['Record uncertainty','Avoid false certainty'],['Test alternative view','Challenge first conclusion']],'Structured review makes a conclusion harder to cherry-pick.','Look for evidence that could change your mind.'),
  b('Expert','Match each rest-defence role to its key job.',[['Nearest cover','Support counter-press'],['Central protector','Block direct route to goal'],['Far-side defender','Control switch and depth'],['Goalkeeper','Sweep space behind']],'Rest defence protects different counter routes before the loss.','Build the safety net while attacking.'),
  b('Expert','Match each half-space action to what it can create.',[['Eight arrives late','Untracked box entry'],['Winger receives inside','Shooting or through-pass angle'],['Full-back underlaps','Runner inside wide defender'],['Striker drifts across','Overload between defenders']],'The inside channel offers angles between centre and wing.','Combine inside access with outside width.'),
  b('Expert','Match each third-player role to the action.',[['First passer','Starts the combination'],['Bounce player','Sets away from pressure'],['Third runner','Receives facing forward'],['Cover player','Protects if the move breaks']],'A third-player move releases someone not directly marked by the first defender.','Pass, set, arrive—while staying protected.'),
  b('Expert','Match each double-pivot movement to the balance it creates.',[['One drops','Supports first build-up line'],['One advances','Occupies next line'],['One slides across','Protects ball side'],['One holds','Secures centre behind movement']],'The pair works through different heights and complementary jobs.','Do not remove both pivots with one movement.'),
  b('Expert','Match each man-oriented pressing risk to its answer.',[['Marker dragged wide','Pass responsibility or protect centre'],['Rotation crosses references','Communicate the exchange'],['Duel is lost','Provide cover behind'],['Far-side switch','Narrow then travel early']],'Man references still need limits, cover and shared communication.','Follow threats without losing the team.'),
  b('Expert','Match each zonal-defending idea to its responsibility.',[['Protect zone','Own dangerous space'],['Track entry','React to runner in that space'],['Attack delivery','Win first contact'],['Push out','Reset for second phase']],'Zonal marking uses space as the starting reference, not an excuse to ignore runners.','Zone, runner, ball, reset.'),
  b('Expert','Match each low-block line to its main protection.',[['Front line','Guide first progression'],['Midfield line','Close central access'],['Back line','Control box and depth'],['Far-side unit','Narrow against switches']],'A compact block has connected work on ball, centre, depth and far side.','One line cannot defend the pitch alone.'),
  b('Expert','Match each counter-attack lane to its advantage.',[['Ball-carrier lane','Fix central defender'],['Outside lane','Stretch the covering defender'],['Inside support lane','Offer pass behind pressure'],['Trailing lane','Attack cut-back or second ball']],'Different lanes force different defensive choices.','Fast does not mean crowded.'),
  b('Expert','Match each box-defence job to its danger.',[['Near defender','First contact'],['Central cover','Main goal lane'],['Far defender','Blind-side runner'],['Edge midfielder','Cut-back and second ball']],'Good box defence protects delivery zones and the next phase.','Defend the spaces the cross can reach.'),
  b('Expert','Match each goalkeeper-sweep cue to the decision it affects.',[['Passer under pressure','Likely ball quality'],['Attacker head start','Race access'],['Ball speed','Interception timing'],['Goal distance','Risk of leaving goal']],'Sweeping is a four-part access and risk judgement.','Read the whole race.'),
  b('Expert','Match each expected-goals phrase to its meaning.',[['0.10 xG chance','Roughly one-in-ten model estimate'],['Team xG total','Sum of modelled chance values'],['Different provider','May use different model'],['Single shot outcome','Not guaranteed by probability']],'xG describes estimated chance quality, not a promised result.','Probability is not destiny.'),
  b('Expert','Match each sample problem to the bias it can create.',[['Only highlights','Success-selection bias'],['Only one opponent level','Context bias'],['Missing low-minute games','Availability bias'],['Role changes mixed together','Role-confounding bias']],'Samples can mislead through what they include or combine.','Ask what is missing.'),
  b('Expert','Match each recruitment input to the decision question.',[['Role fit','Can the player do our job?'],['Age curve','How may the profile change?'],['Contract cost','What is the resource trade-off?'],['Evidence confidence','How sure are we?']],'Recruitment combines football, timeline, money and uncertainty.','The best player is not automatically the best signing.'),
  b('Expert','Match each tactical-analysis layer to its focus.',[['Structure','Where players begin'],['Movement','How the picture changes'],['Decision','Why an option is chosen'],['Execution','How well the action is performed']],'Separating layers helps identify the real problem.','Do not coach technique when the route never existed.'),
  b('Expert','Match each set-piece metric to what it reveals.',[['First-contact rate','Access to delivery'],['Shot rate','Chance creation after delivery'],['Counter conceded','Rest-defence risk'],['Second-ball recovery','Continuation control']],'Set-piece performance includes entry, chance, safety and continuation.','Do not judge routines by goals alone.'),
  b('Expert','Match each game-state change to a tactical effect.',[['Opponent adds striker','More depth and box threat'],['Opponent removes winger','Possible loss of width'],['Your team takes lead','Risk balance can change'],['Red card shown','Coverage and workload change']],'Changes alter space, numbers and acceptable risk.','Re-read the match after every major change.'),
  b('Sharp','Match each player-development stage to its question.',[['Baseline','Where are we now?'],['Objective','What should improve?'],['Practice plan','How will we train it?'],['Review point','What changed and what is next?']],'Development is clearer when the goal and review are measurable.','Plan the next step from evidence.'),
]

const permutations=[[2,0,3,1],[1,3,0,2],[3,1,2,0],[0,2,1,3]] as const
const framings=['','New board: ','Mastery board: ','Final link check: '] as const
function buildQuestion(board:Board,boardIndex:number,variant:number,questionIndex:number):LinkQuestion{
  const pairs=board.pairs.map(([left,right])=>({left,right}))
  return { id:`link-${String(questionIndex+1).padStart(3,'0')}`,kind:'link-up',difficulty:board.difficulty,prompt:`${framings[variant]}${board.prompt}`,pairs,rightOptions:permutations[(boardIndex+variant)%4].map(index=>pairs[index]!.right),explanation:board.explanation,takeaway:board.takeaway }
}
export const linkUpQuestionBank:LinkQuestion[]=Array.from({length:4},(_,variant)=>boards.map((board,index)=>buildQuestion(board,index,variant,variant*boards.length+index))).flat()
