-- Account-backed private leagues for the Player Market beta.

create table if not exists public.market_friend_leagues (
  id bigint generated by default as identity primary key,
  league_code text not null unique check (league_code ~ '^[A-Z0-9]{8}$'),
  name text not null check (char_length(name) between 3 and 40),
  owner_user_id uuid not null references auth.users(id) on delete cascade,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.market_friend_league_members (
  league_id bigint not null references public.market_friend_leagues(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null default 'member' check (role in ('owner', 'member')),
  joined_at timestamptz not null default now(),
  primary key (league_id, user_id)
);

create index if not exists market_friend_league_members_user_idx
  on public.market_friend_league_members(user_id, joined_at desc);

alter table public.market_friend_leagues enable row level security;
alter table public.market_friend_league_members enable row level security;

create or replace function public.market_is_friend_league_member(p_league_id bigint)
returns boolean
language sql
stable
security definer
set search_path = pg_catalog, public
as $$
  select exists (
    select 1
    from public.market_friend_league_members member
    where member.league_id = p_league_id
      and member.user_id = auth.uid()
  )
$$;

revoke all on function public.market_is_friend_league_member(bigint) from public, anon, authenticated, service_role;
grant execute on function public.market_is_friend_league_member(bigint) to authenticated;

drop policy if exists market_friend_leagues_member_read on public.market_friend_leagues;
create policy market_friend_leagues_member_read
  on public.market_friend_leagues for select
  to authenticated
  using (public.market_is_friend_league_member(id));

drop policy if exists market_friend_league_members_member_read on public.market_friend_league_members;
create policy market_friend_league_members_member_read
  on public.market_friend_league_members for select
  to authenticated
  using (public.market_is_friend_league_member(league_id));

revoke all on table public.market_friend_leagues from public, anon, authenticated;
revoke all on table public.market_friend_league_members from public, anon, authenticated;
grant select on table public.market_friend_leagues to authenticated;
grant select on table public.market_friend_league_members to authenticated;

create or replace function public.market_create_friend_league(p_name text)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  uid uuid := auth.uid();
  clean_name text := btrim(p_name);
  new_league public.market_friend_leagues%rowtype;
  candidate_code text;
begin
  if uid is null then raise exception 'Not authenticated'; end if;
  if char_length(clean_name) < 3 or char_length(clean_name) > 40 then
    raise exception 'League name must be between 3 and 40 characters';
  end if;

  loop
    candidate_code := upper(substr(md5(gen_random_uuid()::text), 1, 8));
    exit when not exists (
      select 1 from public.market_friend_leagues where league_code = candidate_code
    );
  end loop;

  insert into public.market_friend_leagues(league_code, name, owner_user_id)
  values (candidate_code, clean_name, uid)
  returning * into new_league;

  insert into public.market_friend_league_members(league_id, user_id, role)
  values (new_league.id, uid, 'owner');

  return to_jsonb(new_league);
end;
$$;

create or replace function public.market_join_friend_league(p_league_code text)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  uid uuid := auth.uid();
  target_league public.market_friend_leagues%rowtype;
begin
  if uid is null then raise exception 'Not authenticated'; end if;

  select * into target_league
  from public.market_friend_leagues
  where league_code = upper(btrim(p_league_code)) and is_active
  limit 1;

  if target_league.id is null then raise exception 'League code not found'; end if;

  insert into public.market_friend_league_members(league_id, user_id, role)
  values (target_league.id, uid, case when target_league.owner_user_id = uid then 'owner' else 'member' end)
  on conflict (league_id, user_id) do nothing;

  return to_jsonb(target_league);
end;
$$;

create or replace function public.market_leave_friend_league(p_league_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  uid uuid := auth.uid();
begin
  if uid is null then raise exception 'Not authenticated'; end if;
  if exists (
    select 1 from public.market_friend_leagues
    where id = p_league_id and owner_user_id = uid
  ) then
    raise exception 'League owners cannot leave their own league';
  end if;

  delete from public.market_friend_league_members
  where league_id = p_league_id and user_id = uid;

  return jsonb_build_object('left', found, 'league_id', p_league_id);
end;
$$;

revoke all on function public.market_create_friend_league(text) from public, anon, authenticated, service_role;
revoke all on function public.market_join_friend_league(text) from public, anon, authenticated, service_role;
revoke all on function public.market_leave_friend_league(bigint) from public, anon, authenticated, service_role;
grant execute on function public.market_create_friend_league(text) to authenticated;
grant execute on function public.market_join_friend_league(text) to authenticated;
grant execute on function public.market_leave_friend_league(bigint) to authenticated;

create or replace view public.market_friend_league_leaderboard as
select
  league.id as league_id,
  league.name as league_name,
  league.league_code,
  league.owner_user_id,
  member.user_id,
  profile.username,
  coalesce(portfolio.total_portfolio_value_minor, 100000000) as total_account_value,
  coalesce(portfolio.realised_profit_minor, 0) as realized_profit_loss,
  coalesce(portfolio.current_holdings_value_minor, 0) as portfolio_value,
  rank() over (
    partition by league.id
    order by coalesce(portfolio.total_portfolio_value_minor, 100000000) desc, member.joined_at asc
  )::integer as rank
from public.market_friend_leagues league
join public.market_friend_league_members member on member.league_id = league.id
left join public.profiles profile on profile.id = member.user_id
left join public.market_portfolios portfolio on portfolio.user_id = member.user_id
where league.is_active
  and public.market_is_friend_league_member(league.id);

revoke all on table public.market_friend_league_leaderboard from public, anon, authenticated;
grant select on table public.market_friend_league_leaderboard to authenticated;
