-- FootballIQ Player Market MVP schema + atomic trade RPCs
-- Manual apply only. Do not auto-run in production pipelines.
-- Safe to review and apply in Supabase SQL editor.

begin;

-- Core player catalog (public-readable active rows only).
create table if not exists public.market_players (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  display_name text not null,
  short_name text,
  club_name text not null,
  position text not null check (position in ('GK','DEF','MID','FWD')),
  nationality text,
  active boolean not null default true,
  current_value bigint not null check (current_value >= 0),
  previous_value bigint not null check (previous_value >= 0),
  opening_season_value bigint not null check (opening_season_value >= 0),
  value_updated_at timestamptz not null default now(),
  data_updated_at timestamptz not null default now(),
  data_source_label text not null,
  source_reference text,
  provenance_status text not null default 'owner_seed_demo',
  owner_verified boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.player_season_stats (
  id bigint generated by default as identity primary key,
  player_id bigint not null references public.market_players(id) on delete cascade,
  season text not null,
  competition_label text not null,
  appearances integer,
  starts integer,
  minutes integer,
  goals integer,
  assists integer,
  clean_sheets integer,
  yellow_cards integer,
  red_cards integer,
  shots integer,
  shots_on_target integer,
  chances_created integer,
  key_passes integer,
  passes_completed integer,
  pass_accuracy numeric(5,2),
  tackles integer,
  interceptions integer,
  clearances integer,
  blocks integer,
  saves integer,
  goals_conceded integer,
  expected_goals numeric(6,3),
  expected_assists numeric(6,3),
  average_rating numeric(4,2),
  data_source text not null,
  source_reference text,
  provenance_status text not null default 'owner_seed_demo',
  owner_verified boolean not null default false,
  last_verified_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(player_id, season, competition_label)
);

create table if not exists public.market_portfolios (
  user_id uuid primary key references auth.users(id) on delete cascade,
  available_balance bigint not null default 100000000 check (available_balance >= 0),
  starting_balance bigint not null default 100000000 check (starting_balance > 0),
  portfolio_value bigint not null default 0 check (portfolio_value >= 0),
  total_account_value bigint not null default 100000000 check (total_account_value >= 0),
  realized_profit_loss bigint not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.market_holdings (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  player_id bigint not null references public.market_players(id) on delete cascade,
  acquisition_value bigint not null check (acquisition_value >= 0),
  acquired_at timestamptz not null default now(),
  current_value_snapshot bigint not null check (current_value_snapshot >= 0),
  unrealized_profit_loss bigint not null default 0,
  unique(user_id, player_id)
);

create table if not exists public.market_transactions (
  id bigint generated by default as identity primary key,
  transaction_id text not null unique default ('mkt-' || substr(md5(random()::text || clock_timestamp()::text), 1, 16)),
  user_id uuid not null references auth.users(id) on delete cascade,
  player_id bigint not null references public.market_players(id) on delete restrict,
  transaction_type text not null check (transaction_type in ('buy', 'sell')),
  execution_value bigint not null check (execution_value >= 0),
  balance_before bigint not null check (balance_before >= 0),
  balance_after bigint not null check (balance_after >= 0),
  created_at timestamptz not null default now(),
  trade_date_utc date not null default ((now() at time zone 'UTC')::date),
  idempotency_key text not null,
  unique(user_id, idempotency_key)
);

create table if not exists public.market_value_history (
  id bigint generated by default as identity primary key,
  player_id bigint not null references public.market_players(id) on delete cascade,
  value bigint not null check (value >= 0),
  recorded_at timestamptz not null default now(),
  reason_category text not null,
  methodology_version text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.market_watchlist (
  user_id uuid not null references auth.users(id) on delete cascade,
  player_id bigint not null references public.market_players(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, player_id)
);

create table if not exists public.market_portfolio_snapshots (
  user_id uuid not null references auth.users(id) on delete cascade,
  snapshot_date date not null,
  available_balance bigint not null,
  portfolio_value bigint not null,
  total_account_value bigint not null,
  created_at timestamptz not null default now(),
  primary key (user_id, snapshot_date)
);

create table if not exists public.market_xp_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  event_code text not null,
  xp_awarded integer not null check (xp_awarded >= 0),
  created_at timestamptz not null default now(),
  unique(user_id, event_code)
);

create table if not exists public.market_settings (
  singleton boolean primary key default true check (singleton = true),
  market_status text not null default 'open' check (market_status in ('open', 'updating', 'paused')),
  methodology_version text not null default 'v1.0.0',
  last_market_update_at timestamptz,
  updated_at timestamptz not null default now()
);

insert into public.market_settings(singleton)
values (true)
on conflict (singleton) do nothing;

-- Indexes
create index if not exists market_players_active_idx on public.market_players(active, current_value desc);
create index if not exists market_players_position_idx on public.market_players(position, current_value desc);
create index if not exists market_players_club_idx on public.market_players(club_name);
create index if not exists market_players_value_updated_idx on public.market_players(value_updated_at desc);
create index if not exists player_season_stats_player_idx on public.player_season_stats(player_id, season);
create index if not exists market_holdings_user_idx on public.market_holdings(user_id);
create index if not exists market_transactions_user_date_idx on public.market_transactions(user_id, trade_date_utc, transaction_type);
create index if not exists market_transactions_player_created_idx on public.market_transactions(player_id, created_at desc);
create index if not exists market_value_history_player_recorded_idx on public.market_value_history(player_id, recorded_at desc);
create index if not exists market_watchlist_user_idx on public.market_watchlist(user_id, created_at desc);
create index if not exists market_portfolio_snapshots_date_idx on public.market_portfolio_snapshots(snapshot_date desc);

-- Updated-at helper trigger.
create or replace function public.market_set_updated_at()
returns trigger language plpgsql set search_path = public as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists market_players_set_updated_at on public.market_players;
create trigger market_players_set_updated_at
before update on public.market_players
for each row execute function public.market_set_updated_at();

drop trigger if exists player_season_stats_set_updated_at on public.player_season_stats;
create trigger player_season_stats_set_updated_at
before update on public.player_season_stats
for each row execute function public.market_set_updated_at();

drop trigger if exists market_portfolios_set_updated_at on public.market_portfolios;
create trigger market_portfolios_set_updated_at
before update on public.market_portfolios
for each row execute function public.market_set_updated_at();

drop trigger if exists market_settings_set_updated_at on public.market_settings;
create trigger market_settings_set_updated_at
before update on public.market_settings
for each row execute function public.market_set_updated_at();

-- RLS
alter table public.market_players enable row level security;
alter table public.player_season_stats enable row level security;
alter table public.market_portfolios enable row level security;
alter table public.market_holdings enable row level security;
alter table public.market_transactions enable row level security;
alter table public.market_value_history enable row level security;
alter table public.market_watchlist enable row level security;
alter table public.market_portfolio_snapshots enable row level security;
alter table public.market_xp_events enable row level security;
alter table public.market_settings enable row level security;

-- Public browsing policies (active approved entities only).
drop policy if exists "Public can read active market players" on public.market_players;
create policy "Public can read active market players"
on public.market_players for select
using (active = true);

drop policy if exists "Public can read approved season stats" on public.player_season_stats;
create policy "Public can read approved season stats"
on public.player_season_stats for select
using (
  exists (
    select 1 from public.market_players p
    where p.id = player_season_stats.player_id and p.active = true
  )
);

drop policy if exists "Public can read value history for active players" on public.market_value_history;
create policy "Public can read value history for active players"
on public.market_value_history for select
using (
  exists (
    select 1 from public.market_players p
    where p.id = market_value_history.player_id and p.active = true
  )
);

drop policy if exists "Public can read market settings" on public.market_settings;
create policy "Public can read market settings"
on public.market_settings for select
using (true);

-- Owner-only private data policies.
drop policy if exists "Users read own market portfolio" on public.market_portfolios;
create policy "Users read own market portfolio"
on public.market_portfolios for select
using (auth.uid() = user_id);

drop policy if exists "Users update own market portfolio" on public.market_portfolios;
create policy "Users update own market portfolio"
on public.market_portfolios for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "Users insert own market portfolio" on public.market_portfolios;
create policy "Users insert own market portfolio"
on public.market_portfolios for insert
with check (auth.uid() = user_id);

drop policy if exists "Users read own holdings" on public.market_holdings;
create policy "Users read own holdings"
on public.market_holdings for select
using (auth.uid() = user_id);

drop policy if exists "Users insert own holdings" on public.market_holdings;
create policy "Users insert own holdings"
on public.market_holdings for insert
with check (auth.uid() = user_id);

drop policy if exists "Users update own holdings" on public.market_holdings;
create policy "Users update own holdings"
on public.market_holdings for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "Users delete own holdings" on public.market_holdings;
create policy "Users delete own holdings"
on public.market_holdings for delete
using (auth.uid() = user_id);

drop policy if exists "Users read own market transactions" on public.market_transactions;
create policy "Users read own market transactions"
on public.market_transactions for select
using (auth.uid() = user_id);

drop policy if exists "Users insert own market transactions" on public.market_transactions;
create policy "Users insert own market transactions"
on public.market_transactions for insert
with check (auth.uid() = user_id);

drop policy if exists "Users read own watchlist" on public.market_watchlist;
create policy "Users read own watchlist"
on public.market_watchlist for select
using (auth.uid() = user_id);

drop policy if exists "Users write own watchlist" on public.market_watchlist;
create policy "Users write own watchlist"
on public.market_watchlist for insert
with check (auth.uid() = user_id);

drop policy if exists "Users delete own watchlist" on public.market_watchlist;
create policy "Users delete own watchlist"
on public.market_watchlist for delete
using (auth.uid() = user_id);

drop policy if exists "Users read own snapshot rows" on public.market_portfolio_snapshots;
create policy "Users read own snapshot rows"
on public.market_portfolio_snapshots for select
using (auth.uid() = user_id);

drop policy if exists "Users read own market xp events" on public.market_xp_events;
create policy "Users read own market xp events"
on public.market_xp_events for select
using (auth.uid() = user_id);

-- Internal helper: create/get portfolio row.
create or replace function public.market_ensure_portfolio(p_user_id uuid)
returns public.market_portfolios
language plpgsql
security definer
set search_path = public
as $$
declare
  p public.market_portfolios;
begin
  insert into public.market_portfolios(user_id)
  values (p_user_id)
  on conflict (user_id) do nothing;

  select * into p
  from public.market_portfolios
  where user_id = p_user_id;

  return p;
end;
$$;

-- Internal helper: refresh holding snapshots + portfolio totals.
create or replace function public.market_recalculate_portfolio_totals(p_user_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  current_portfolio_value bigint := 0;
  current_total_value bigint := 0;
  current_balance bigint := 0;
begin
  update public.market_holdings h
  set
    current_value_snapshot = p.current_value,
    unrealized_profit_loss = p.current_value - h.acquisition_value
  from public.market_players p
  where h.player_id = p.id
    and h.user_id = p_user_id;

  select coalesce(sum(h.current_value_snapshot), 0)
  into current_portfolio_value
  from public.market_holdings h
  where h.user_id = p_user_id;

  select available_balance
  into current_balance
  from public.market_portfolios
  where user_id = p_user_id;

  current_total_value := current_balance + current_portfolio_value;

  update public.market_portfolios
  set
    portfolio_value = current_portfolio_value,
    total_account_value = current_total_value
  where user_id = p_user_id;
end;
$$;

-- Internal helper: snapshot today.
create or replace function public.market_capture_snapshot(p_user_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  d date := (now() at time zone 'UTC')::date;
  p public.market_portfolios;
begin
  select * into p
  from public.market_portfolios
  where user_id = p_user_id;

  if p.user_id is null then
    return;
  end if;

  insert into public.market_portfolio_snapshots(
    user_id, snapshot_date, available_balance, portfolio_value, total_account_value
  )
  values (p.user_id, d, p.available_balance, p.portfolio_value, p.total_account_value)
  on conflict (user_id, snapshot_date)
  do update set
    available_balance = excluded.available_balance,
    portfolio_value = excluded.portfolio_value,
    total_account_value = excluded.total_account_value,
    created_at = now();
end;
$$;

-- Internal helper: one-time XP milestone awards.
create or replace function public.market_award_xp_event(
  p_user_id uuid,
  p_event_code text,
  p_xp integer
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  inserted_count integer := 0;
begin
  if p_xp <= 0 then
    return false;
  end if;

  insert into public.market_xp_events(user_id, event_code, xp_awarded)
  values (p_user_id, p_event_code, p_xp)
  on conflict (user_id, event_code) do nothing;

  get diagnostics inserted_count = row_count;

  if inserted_count = 0 then
    return false;
  end if;

  update public.profiles
  set xp = xp + p_xp
  where id = p_user_id;

  return true;
end;
$$;

-- Atomic buy RPC.
drop function if exists public.market_buy_player(text, text);
create or replace function public.market_buy_player(
  p_player_slug text,
  p_idempotency_key text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  uid uuid := auth.uid();
  market_status text;
  today_utc date := (now() at time zone 'UTC')::date;
  p public.market_portfolios;
  player_row public.market_players;
  holdings_count integer := 0;
  todays_buys integer := 0;
  duplicate_tx public.market_transactions;
  tx public.market_transactions;
  buy_value bigint := 0;
begin
  if uid is null then
    raise exception 'Not authenticated';
  end if;

  if coalesce(length(trim(p_idempotency_key)), 0) < 8 then
    raise exception 'Invalid idempotency key';
  end if;

  select market_settings.market_status into market_status
  from public.market_settings
  where singleton = true;

  if market_status is distinct from 'open' then
    raise exception 'Market is currently paused or updating';
  end if;

  select * into duplicate_tx
  from public.market_transactions
  where user_id = uid
    and idempotency_key = p_idempotency_key
  limit 1;

  if duplicate_tx.id is not null then
    perform public.market_ensure_portfolio(uid);
    perform public.market_recalculate_portfolio_totals(uid);
    return jsonb_build_object(
      'ok', true,
      'duplicate', true,
      'message', 'Duplicate request ignored',
      'transaction_id', duplicate_tx.transaction_id
    );
  end if;

  perform public.market_ensure_portfolio(uid);

  select * into p
  from public.market_portfolios
  where user_id = uid
  for update;

  select * into player_row
  from public.market_players
  where slug = p_player_slug
  for update;

  if player_row.id is null then
    raise exception 'Player not found';
  end if;

  if not player_row.active then
    raise exception 'Player is inactive';
  end if;

  buy_value := player_row.current_value;

  select count(*) into holdings_count
  from public.market_holdings
  where user_id = uid;

  if holdings_count >= 5 then
    raise exception 'Portfolio is full (maximum 5 players)';
  end if;

  if exists (
    select 1 from public.market_holdings
    where user_id = uid and player_id = player_row.id
  ) then
    raise exception 'Player already owned';
  end if;

  select count(*) into todays_buys
  from public.market_transactions
  where user_id = uid
    and trade_date_utc = today_utc
    and transaction_type = 'buy';

  if todays_buys >= 3 then
    raise exception 'Daily buy limit reached';
  end if;

  if p.available_balance < buy_value then
    raise exception 'Insufficient balance';
  end if;

  insert into public.market_holdings(
    user_id,
    player_id,
    acquisition_value,
    current_value_snapshot,
    unrealized_profit_loss
  )
  values (uid, player_row.id, buy_value, buy_value, 0);

  insert into public.market_transactions(
    user_id,
    player_id,
    transaction_type,
    execution_value,
    balance_before,
    balance_after,
    idempotency_key
  )
  values (
    uid,
    player_row.id,
    'buy',
    buy_value,
    p.available_balance,
    p.available_balance - buy_value,
    p_idempotency_key
  )
  returning * into tx;

  update public.market_portfolios
  set available_balance = p.available_balance - buy_value
  where user_id = uid;

  perform public.market_recalculate_portfolio_totals(uid);
  perform public.market_capture_snapshot(uid);

  perform public.market_award_xp_event(uid, 'market_first_buy', 25);

  select count(*) into holdings_count
  from public.market_holdings
  where user_id = uid;

  if holdings_count = 5 then
    perform public.market_award_xp_event(uid, 'market_first_full_portfolio', 50);
  end if;

  return jsonb_build_object(
    'ok', true,
    'duplicate', false,
    'message', 'Buy executed',
    'transaction_id', tx.transaction_id,
    'player_slug', player_row.slug,
    'execution_value', buy_value
  );
exception
  when unique_violation then
    if exists (
      select 1 from public.market_transactions
      where user_id = uid and idempotency_key = p_idempotency_key
    ) then
      return jsonb_build_object('ok', true, 'duplicate', true, 'message', 'Duplicate request ignored');
    end if;
    raise exception 'Buy blocked by uniqueness guard';
end;
$$;

-- Atomic sell RPC.
drop function if exists public.market_sell_player(text, text);
create or replace function public.market_sell_player(
  p_player_slug text,
  p_idempotency_key text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  uid uuid := auth.uid();
  market_status text;
  today_utc date := (now() at time zone 'UTC')::date;
  p public.market_portfolios;
  player_row public.market_players;
  holding_row public.market_holdings;
  todays_sales integer := 0;
  duplicate_tx public.market_transactions;
  tx public.market_transactions;
  sell_value bigint := 0;
  pnl bigint := 0;
begin
  if uid is null then
    raise exception 'Not authenticated';
  end if;

  if coalesce(length(trim(p_idempotency_key)), 0) < 8 then
    raise exception 'Invalid idempotency key';
  end if;

  select market_settings.market_status into market_status
  from public.market_settings
  where singleton = true;

  if market_status is distinct from 'open' then
    raise exception 'Market is currently paused or updating';
  end if;

  select * into duplicate_tx
  from public.market_transactions
  where user_id = uid
    and idempotency_key = p_idempotency_key
  limit 1;

  if duplicate_tx.id is not null then
    perform public.market_ensure_portfolio(uid);
    perform public.market_recalculate_portfolio_totals(uid);
    return jsonb_build_object(
      'ok', true,
      'duplicate', true,
      'message', 'Duplicate request ignored',
      'transaction_id', duplicate_tx.transaction_id
    );
  end if;

  perform public.market_ensure_portfolio(uid);

  select * into p
  from public.market_portfolios
  where user_id = uid
  for update;

  select * into player_row
  from public.market_players
  where slug = p_player_slug
  for update;

  if player_row.id is null then
    raise exception 'Player not found';
  end if;

  if not player_row.active then
    raise exception 'Player is inactive';
  end if;

  select * into holding_row
  from public.market_holdings
  where user_id = uid and player_id = player_row.id
  for update;

  if holding_row.id is null then
    raise exception 'Cannot sell: player not owned';
  end if;

  select count(*) into todays_sales
  from public.market_transactions
  where user_id = uid
    and trade_date_utc = today_utc
    and transaction_type = 'sell';

  if todays_sales >= 3 then
    raise exception 'Daily sell limit reached';
  end if;

  sell_value := player_row.current_value;
  pnl := sell_value - holding_row.acquisition_value;

  delete from public.market_holdings
  where id = holding_row.id;

  insert into public.market_transactions(
    user_id,
    player_id,
    transaction_type,
    execution_value,
    balance_before,
    balance_after,
    idempotency_key
  )
  values (
    uid,
    player_row.id,
    'sell',
    sell_value,
    p.available_balance,
    p.available_balance + sell_value,
    p_idempotency_key
  )
  returning * into tx;

  update public.market_portfolios
  set
    available_balance = p.available_balance + sell_value,
    realized_profit_loss = realized_profit_loss + pnl
  where user_id = uid;

  perform public.market_recalculate_portfolio_totals(uid);
  perform public.market_capture_snapshot(uid);

  if pnl > 0 then
    perform public.market_award_xp_event(uid, 'market_first_profitable_sale', 40);
  end if;

  return jsonb_build_object(
    'ok', true,
    'duplicate', false,
    'message', 'Sale executed',
    'transaction_id', tx.transaction_id,
    'player_slug', player_row.slug,
    'execution_value', sell_value,
    'profit_loss', pnl
  );
exception
  when unique_violation then
    if exists (
      select 1 from public.market_transactions
      where user_id = uid and idempotency_key = p_idempotency_key
    ) then
      return jsonb_build_object('ok', true, 'duplicate', true, 'message', 'Duplicate request ignored');
    end if;
    raise exception 'Sell blocked by uniqueness guard';
end;
$$;

-- Watchlist helper RPC.
drop function if exists public.market_toggle_watchlist(text);
create or replace function public.market_toggle_watchlist(p_player_slug text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  uid uuid := auth.uid();
  player_row public.market_players;
begin
  if uid is null then
    raise exception 'Not authenticated';
  end if;

  select * into player_row
  from public.market_players
  where slug = p_player_slug;

  if player_row.id is null then
    raise exception 'Player not found';
  end if;

  if exists (
    select 1 from public.market_watchlist
    where user_id = uid and player_id = player_row.id
  ) then
    delete from public.market_watchlist
    where user_id = uid and player_id = player_row.id;
    return jsonb_build_object('watchlisted', false);
  end if;

  insert into public.market_watchlist(user_id, player_id)
  values (uid, player_row.id)
  on conflict (user_id, player_id) do nothing;

  return jsonb_build_object('watchlisted', true);
end;
$$;

-- Portfolio + holdings refresh utility (safe for authenticated user).
drop function if exists public.market_refresh_my_portfolio();
create or replace function public.market_refresh_my_portfolio()
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  uid uuid := auth.uid();
begin
  if uid is null then
    raise exception 'Not authenticated';
  end if;
  perform public.market_ensure_portfolio(uid);
  perform public.market_recalculate_portfolio_totals(uid);
  perform public.market_capture_snapshot(uid);
end;
$$;

-- Admin-safe price update command with preview mode.
-- This function is intentionally restricted to service_role JWT context.
drop function if exists public.market_admin_update_player_value(text, bigint, text, text, boolean);
create or replace function public.market_admin_update_player_value(
  p_player_slug text,
  p_new_value bigint,
  p_reason_category text,
  p_methodology_version text,
  p_apply boolean default false
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  jwt_role text := coalesce(auth.jwt() ->> 'role', 'anon');
  player_row public.market_players;
  rounded_value bigint;
  delta bigint;
begin
  if jwt_role <> 'service_role' then
    raise exception 'Forbidden: service role required';
  end if;

  if p_new_value < 0 then
    raise exception 'Invalid value';
  end if;

  select * into player_row
  from public.market_players
  where slug = p_player_slug
  for update;

  if player_row.id is null then
    raise exception 'Player not found';
  end if;

  rounded_value := (round(p_new_value::numeric / 100000) * 100000)::bigint;
  delta := rounded_value - player_row.current_value;

  if p_apply then
    update public.market_players
    set
      previous_value = player_row.current_value,
      current_value = rounded_value,
      value_updated_at = now()
    where id = player_row.id;

    insert into public.market_value_history(player_id, value, reason_category, methodology_version)
    values (player_row.id, rounded_value, p_reason_category, p_methodology_version);

    update public.market_settings
    set
      methodology_version = p_methodology_version,
      last_market_update_at = now()
    where singleton = true;
  end if;

  return jsonb_build_object(
    'ok', true,
    'applied', p_apply,
    'player_slug', p_player_slug,
    'previous_value', player_row.current_value,
    'new_value', rounded_value,
    'delta', delta,
    'reason_category', p_reason_category,
    'methodology_version', p_methodology_version
  );
end;
$$;

-- Public-safe leaderboard view for Player Market only.
create or replace view public.market_public_leaderboard as
with baseline as (
  select
    p.user_id,
    p.starting_balance,
    p.total_account_value,
    p.total_account_value - p.starting_balance as all_time_gain,
    (now() at time zone 'UTC')::date as today_utc
  from public.market_portfolios p
),
windows as (
  select
    b.user_id,
    b.starting_balance,
    b.total_account_value,
    b.all_time_gain,
    b.today_utc,
    (b.today_utc - 1) as daily_start,
    (b.today_utc - 7) as weekly_start,
    date_trunc('month', b.today_utc)::date as monthly_start,
    make_date(extract(year from b.today_utc)::int, (((extract(quarter from b.today_utc)::int - 1) * 3) + 1), 1) as season_start
  from baseline b
),
joined as (
  select
    w.user_id,
    w.total_account_value,
    w.starting_balance,
    w.all_time_gain,
    coalesce((select s.total_account_value from public.market_portfolio_snapshots s where s.user_id = w.user_id and s.snapshot_date = w.daily_start), w.starting_balance) as daily_base,
    coalesce((select s.total_account_value from public.market_portfolio_snapshots s where s.user_id = w.user_id and s.snapshot_date >= w.weekly_start order by s.snapshot_date asc limit 1), w.starting_balance) as weekly_base,
    coalesce((select s.total_account_value from public.market_portfolio_snapshots s where s.user_id = w.user_id and s.snapshot_date >= w.monthly_start order by s.snapshot_date asc limit 1), w.starting_balance) as monthly_base,
    coalesce((select s.total_account_value from public.market_portfolio_snapshots s where s.user_id = w.user_id and s.snapshot_date >= w.season_start order by s.snapshot_date asc limit 1), w.starting_balance) as season_base
  from windows w
)
select
  pr.id as user_id,
  pr.username,
  j.total_account_value,
  j.all_time_gain,
  (j.total_account_value - j.daily_base) as daily_gain,
  (j.total_account_value - j.weekly_base) as weekly_gain,
  (j.total_account_value - j.monthly_base) as monthly_gain,
  (j.total_account_value - j.season_base) as season_gain,
  case when j.daily_base > 0 then round(((j.total_account_value - j.daily_base)::numeric / j.daily_base::numeric) * 100, 2) else 0 end as daily_return_pct,
  case when j.weekly_base > 0 then round(((j.total_account_value - j.weekly_base)::numeric / j.weekly_base::numeric) * 100, 2) else 0 end as weekly_return_pct,
  case when j.monthly_base > 0 then round(((j.total_account_value - j.monthly_base)::numeric / j.monthly_base::numeric) * 100, 2) else 0 end as monthly_return_pct,
  case when j.season_base > 0 then round(((j.total_account_value - j.season_base)::numeric / j.season_base::numeric) * 100, 2) else 0 end as season_return_pct,
  case when j.starting_balance > 0 then round((j.all_time_gain::numeric / j.starting_balance::numeric) * 100, 2) else 0 end as all_time_return_pct
from joined j
join public.profiles pr on pr.id = j.user_id
where pr.username is not null;

grant select on public.market_public_leaderboard to anon;
grant select on public.market_public_leaderboard to authenticated;

-- Function execution grants.
grant execute on function public.market_buy_player(text, text) to authenticated;
grant execute on function public.market_sell_player(text, text) to authenticated;
grant execute on function public.market_toggle_watchlist(text) to authenticated;
grant execute on function public.market_refresh_my_portfolio() to authenticated;
revoke all on function public.market_ensure_portfolio(uuid) from public, anon, authenticated;
revoke all on function public.market_recalculate_portfolio_totals(uuid) from public, anon, authenticated;
revoke all on function public.market_capture_snapshot(uuid) from public, anon, authenticated;
revoke all on function public.market_award_xp_event(uuid, text, integer) from public, anon, authenticated;
revoke all on function public.market_admin_update_player_value(text, bigint, text, text, boolean) from public, anon, authenticated;
grant execute on function public.market_admin_update_player_value(text, bigint, text, text, boolean) to service_role;

commit;
